<?php
/**
* @version    $Id: config.inc.php,v 2.13 2005/12/06 08:33:35 lechu Exp $
* @package    default
* \@ask4price
*/
// tablice elementow dot. sortowania na listach rekordow
$config->dbedit_order_names=array('main'=>array( "1"=>"user_id",
                                                "-1"=>"user_id DESC",
                                                 "2"=>"name",
                                                "-2"=>"name DESC",
                                                 "3"=>"producer",
                                                "-3"=>"producer DESC",
                                                 "4"=>"category1",
                                                "-4"=>"category1 DESC",
                                                 "5"=>"price_brutto",
                                                "-5"=>"price_brutto DESC",
                                                 "6"=>"photo",
                                                "-6"=>"photo DESC",
                                                "default"=>"name"
                                               ),
                                   'order_register'=>array(
                                                 "1"=>"order_id",
                                                "-1"=>"order_id DESC",
                                                 "2"=>"date_add",
                                                "-2"=>"date_add DESC",
                                                 "3"=>"amount",
                                                "-3"=>"amount DESC",
                                                 "4"=>"id_status",
                                                "-4"=>"id_status DESC",
                                                 "5"=>"cancel,confirm",
                                                "-5"=>"cancel,confirm DESC",
                                                 "6"=>"confirm_online",
                                                "-6"=>"confirm_online DESC",
                                                 "7"=>"id_pay_method",
                                                "-7"=>"id_pay_method DESC",
                                                 "8"=>"partner_id",
                                                "-8"=>"partner_id DESC",
                                                 "9"=>"rake_off_amount",
                                                "-9"=>"rake_off_amount DESC"
                                               ),
                                     'delivery'=>array(
                                                "1"=>"id",
                                               "-1"=>"id DESC",
                                                "2"=>"name",
                                               "-2"=>"name DESC",
                                                "3"=>"free_from",
                                               "-3"=>"free_from DESC",
                                                "4"=>"price_brutto",
                                               "-4"=>"price_brutto DESC", 
                                                "5"=>"order_by",
                                               "-5"=>"order_by DESC"                                              
                                               ),
                                    'available'=>array(
                                    	       "1"=>"user_id",
                                    	      "-1"=>"user_id DESC",
                                    	       "2"=>"name",
                                    	      "-2"=>"name DESC"
                                    	      ),  
                                    'vat'=>array(
                                    			"1"=>"id",
                                               "-1"=>"id DESC",
                                                "3"=>"vat",
                                               "-3"=>"vat DESC"
                                               ),	  
                                    'currency'=>array(
                                    		   	"1"=>"id",
                                    		   "-1"=>"id DESC",
                                    			"2"=>"currency_name",
                                    	       "-2"=>"currency_name DESC",
                                    			"3"=>"currency_val",
                                    		   "-3"=>"currency_val DESC",
                                    		    "4"=>"date_update",
                                    		   "-4"=>"date_update DESC"
                                    			),
                                    'newsletter'=>array(
                                    			"1"=>"id",
                                    			"-1"=>"id DESC",
                                    			"2"=>"email",
                                    			"-2"=>"email DESC",
                                    			"3"=>"date_add",
                                    			"-3"=>"date_add DESC",
                                    			"4"=>"active",
                                    			"-4"=>"active DESC",
                                    			"5"=>"lang",
                                    			"-5"=>"lang DESC",			
                                    	                ),
                                    'main_keys'=>array(
                                                "1"=>"user_id",
                                                "-1"=>"user_id DESC"
                                                      ),
                                    'category1'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"category1","-3"=>"category1 DESC"),
                                                       
                                    'category2'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"category2","-3"=>"category2 DESC"),
                                                       
                                    'category3'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"category3","-3"=>"category3 DESC"),
                                                       
                                    'category4'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"category4","-3"=>"category4 DESC"),
                                                       
                                    'category5'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"category5","-3"=>"category5 DESC"),
                                                       
                                    'producer'=>array("1"=>"id","-1"=>"id DESC",
                                                       "3"=>"producer","-3"=>"producer DESC"),
                                     
                                    'main_keys'=>array("1"=>"id",                                     
                                                       "-1"=>"id DESC",
                                                       "3"=>"user_id_main",
                                                       "-3"=>"user_id_main DESC",
                                                       "5"=>"order_id",
                                                       "-5"=>"order_id DESC"
                                                      ),
                                    'main_keys_ftp'=>array("1"=>"id",
                                                          "-1"=>"id DESC",
                                                          "3"=>"user_id_main",
                                                          "-3"=>"user_id_main DESC",
                                                          "4"=>"ftp",
                                                          "-4"=>"ftp DESC",
                                                          "5"=>"active",
                                                          "-5"=>"active DESC"
                                                          ),
                                    'partners'=>array("1"=>"id",
                                    				  "-1"=>"id DESC",
                                    				  "3"=>"partner_id",
                                    				  "-3"=>"partner_id DESC",					
                                    				  "4"=>"name",
                                    				  "-4"=>"name DESC",
                                    				  "5"=>"www",
                                    				  "-5"=>"www DESC",
                                    				  "6"=>"email",
                                    				  "-6"=>"email DESC",
                                    				  "7"=>"rake_off",
                                    				  "-7"=>"rake_off DESC"	
                                    					),
                                    'reviews'=>array("1"=>"id",
                                    				 "-1"=>"id DESC",
                                    				 "3"=>"user_id",
                                    				 "-3"=>"user_id DESC",
                                    				 "4"=>"author",
                                    				 "-4"=>"author DESC",
                                    				 "5"=>"description",
                                    				 "-5"=>"description DESC",
                                    				 "6"=>"score",
                                    				 "-6"=>"score DESC",
                                    				 "7"=>"date_add",
                                    				 "-7"=>"date_add DESC",
                                    				 "8"=>"state",
                                    				 "-8"=>"state DESC"
                                    				 ),
                                   'scores'=>array("1"=>"id",
                                   			  "-1"=>"id DESC", 				 						                      
                                               "3"=>"id_product",
                                               "-3"=>"id_product DESC",
                                               "4"=>"score_amount",
                                               "-4"=>"score_amount DESC",
                                               "5"=>"scores_number",
                                               "-5"=>"scores_number DESC"  
                                                 ),
                                   'promotions'=>array("1"=>"id",
                                   					   "-1"=>"id DESC",
                                   					   "3"=>"name",
                                   					   "-3"=>"name DESC",
                                   					   "4"=>"active",
                                   					   "-4"=>"active DESC"	
                                   						),
                                   'newsedit'=>array("1"=>"id",
                                                    "-1"=>"id DESC",
                                                    "2"=>"subject",
                                                    "-2"=>"subject DESC",
                                                    "3"=>"date_add",
                                                    "-3"=>"date_add DESC",
                                                    "4"=>"active",
                                                    "-4"=>"active DESC",
                                                    "5"=>"ordercol",
                                                    "-5"=>"ordercol DESC",
                                                    "6"=>"id_newsedit_groups",
                                                    "-6"=>"id_newsedit_groups DESC"
                                                    ),
                                    'order_status'=>array("1"=>"id",
                                                          "-1"=>"id DESC",
                                                          "2"=>"name",
                                                          "-2"=>"name DESC",
                                                          "3"=>"send_mail",
                                                          "-3"=>"send_mail DESC",
                                                          ),
                                    'ask4price'=>array("1"=>"request_id",
                                                      "-1"=>"request_id DESC",
                                                       "3"=>"name_company",
                                                      "-3"=>"name_company DESC",
                                                       "4"=>"email",
                                                      "-4"=>"email DESC",
                                                       "5"=>"id_users",
                                                      "-5"=>"id_users DESC",
                                                       "6"=>"date_add",
                                                      "-6"=>"date_add DESC",
                                                       "7"=>"active",
                                                      "-7"=>"active DESC",
                                                          ),
                                    'depository'=>array(
                                                       "1"=>"id",
                                                      "-1"=>"id DESC",
                                                       "2"=>"user_id_main",
                                                      "-2"=>"user_id_main DESC",
                                                       "3"=>"num",
                                                      "-3"=>"num DESC",
                                                       "4"=>"min_num",
                                                      "-4"=>"min_num DESC",
                                                       "5"=>"diff",
                                                      "-5"=>"diff DESC",
                                                       "6"=>"id_deliverer",
                                                      "-6"=>"id_deliverer DESC",
                                                          ),
                                 	  );
?>
