<?php


class MyConfig extends AutoConfig{
	var $db=array(
                'nobody_dbuser'=>"%F1%7D%DD5",
                'nobody_dbpassword'=>"%F3e%CC%22%03%DC",
                'admin_dbuser'=>"%CE%BC2%97",
                'admin_dbpassword'=>"%CC%A4%23%802%07",
                'dbhost'=>"%EE%7D%CA1%1B%CDI%C7%2B",
                'dbname'=>"%F1%7D%DD5%12%D6M%D8%3A%A6v",
                );
	var $ftp=array(
                'ftp_host'=>"localhost",
                'ftp_user'=>"maroslaw",
                'ftp_password'=>"%F7%96%02%B7%08%3B%A5C%D58",
                'ftp_dir'=>"/usr/home/maroslaw/MYCVS/soteesklep2",
                );
	var $salt="f37e02d876032f4335ceb2c97a4b831c";
	var $md5_pin="81dc9bdb52d04dc20036dbd8313ed055";
	var $license=array(
                'nr'=>"2005-0615-0001-0001-c666-0086",
                'who'=>"SOTE",
                );
	var $auth_sign=array(
                'b1df8666fbf0c63040abc625e2ed8e69'=>"admin",
                );
	var $config_setup=array(
                'type'=>"simple",
                'os'=>"linux",
                'host'=>"local",
                );
	var $order_points="22";
	var $available=array(
                '1'=>"jest",
                '2'=>"2 dni",
                '8'=>"8 dni",
                '9'=>"14 dni",
                );
	var $currency_data=array(
                '1'=>"1",
                '2'=>"4.12",
                '5'=>"0.1157",
                '4'=>"0.1379",
                '3'=>"3.22",
                );
	var $currency_name=array(
                '1'=>"PLN",
                '2'=>"EUR",
                '5'=>"RUB",
                '4'=>"CZK",
                '3'=>"USD",
                );
	var $category=array(
                'icons'=>"1",
                'type'=>"treeview",
                'openall'=>"1",
                );
	var $stats=array(
                'url'=>"",
                );
	var $merchant=array(
                'name'=>"",
                'addr'=>"",
                'tel'=>"",
                'fax'=>"",
                'nip'=>"",
                'bank'=>"",
                );
	var $order_email="";
	var $from_email="";
	var $newsletter_email="";
	var $www="soteesklep3";
	var $currency="PLN";
	var $cd_setup=array(
                'cd'=>"0",
                'IP'=>"",
                'price'=>"",
                'hurt'=>"",
                );
	var $theme="blue";
	var $themes_active=array(
                'blue'=>"1",
                );
	var $record_row_type_default="long";
	var $producers_category_filter="yes";
	var $google=array(
                'keywords'=>"sklep internetowy",
                'title'=>"SOTEeSKLEP",
                'description'=>"sklep internetowy ",
                );
	var $price_type="netto/brutto";
	var $products_on_page=array(
                'long'=>"10",
                'short'=>"20",
                );
	var $image=array(
                'max_size'=>"300",
                'min_size'=>"115",
                );
	var $main_order_default="producer";
	var $vat_confirm="1";
	var $id_start_orders_default="0";
	var $newsedit_columns_default="2";
	var $lang="pl";
	var $lang_id="0";
	var $lang_active=array(
                'en'=>"1",
                'de'=>"1",
                'pl'=>"1",
                );
	var $currency_lang_default=array(
                'pl'=>"1",
                'en'=>"3",
                'de'=>"2",
                'cz'=>"4",
                'ru'=>"5",
                );
	var $category_multi="1";
	var $newsedit="1";
	var $newsletter="1";
	var $currency_show_form="1";
	var $cyfra_photo="1";
	var $basket_photo="1";
	var $htdocs_lang="pl";
	var $pay_method_active=array(
                '1'=>"1",
                '11'=>"1",
                '12'=>"0",
                '3'=>"0",
                '20'=>"0",
                '101'=>"1",
                );
	var $random_on_page=array(
                'promotion'=>"2",
                'newcol'=>"3",
                'bestseller'=>"2",
                );
	var $themes=array(
                'redball'=>"redball",
                'blueball'=>"blueball",
                'red'=>"red",
                'blue'=>"blue",
                'green'=>"green",
                'brown'=>"brown",
                'blueday'=>"blueday",
                'grayday'=>"grayday",
                'bluelight'=>"bluelight",
                'pinklight'=>"pinklight",
                );
	var $fields="";
	var $editable_themes=array(
                'blue'=>"blue",
                'redball'=>"redball",
                'blueday'=>"blueday",
                'grayday'=>"grayday",
                'bluelight'=>"bluelight",
                'pinklight'=>"pinklight",
                );
	var $admin_lang="pl";
	var $in_category_down="3";
	var $catalog_mode="0";
	var $rss_link="1";
	var $happy_hour="3";
	var $country_select=array(
                'AF'=>"Afganistan",
                'AL'=>"Albania",
                'DZ'=>"Algeria",
                'AD'=>"Andora",
                'AO'=>"Angola",
                'AI'=>"Anguilla",
                'AQ'=>"Andarktyda",
                'AG'=>"Antigua i Barbuda",
                'AN'=>"Antyle holenderskie",
                'SA'=>"Arabia Saudyjska",
                'AR'=>"Argentyna",
                'AM'=>"Armenia",
                'AW'=>"Aruba",
                'AU'=>"Australia",
                'AT'=>"Austria",
                'AZ'=>"Azejberd¿an",
                'BS'=>"Bahamy",
                'BH'=>"Bahrajn",
                'BD'=>"Bangladesz",
                'BB'=>"Barbados",
                'BE'=>"Belgia",
                'BZ'=>"Belize",
                'BJ'=>"Benin",
                'BM'=>"Bermudy",
                'BT'=>"Bhutan",
                'BY'=>"Bia³oru¶",
                'BO'=>"Boliwia",
                'BA'=>"Bo¶nia i Hercegowina",
                'BW'=>"Botswana",
                'BR'=>"Brazylia",
                'BN'=>"Brunei Darussalam",
                'IO'=>"Brytyjskie Terytorium Oceanu Indyjskiego",
                'BG'=>"Bu³garia",
                'BF'=>"Burkina Faso",
                'BI'=>"Burundi",
                'HR'=>"Chorwacja",
                'CL'=>"Chile",
                'CN'=>"Chiny",
                'CY'=>"Cypr",
                'TD'=>"Czad",
                'CZ'=>"Czechy",
                'DK'=>"Dania",
                'DM'=>"Dominika",
                'DO'=>"Dominikana",
                'DJ'=>"D¿ibuti",
                'EG'=>"Egypt",
                'EC'=>"Ekwador",
                'ER'=>"Erytrea",
                'EE'=>"Estonia",
                'ET'=>"Etiopia",
                'FK'=>"Falklandy",
                'FJ'=>"Fid¿i",
                'PH'=>"Filipiny",
                'FI'=>"Finlandia",
                'FR'=>"Francja",
                'TF'=>"Francuskie Terytorium Po³udniowe",
                'GA'=>"Gabon",
                'GM'=>"Gambia",
                'GH'=>"Ghana",
                'GI'=>"Gibraltar",
                'GR'=>"Grecja",
                'GD'=>"Grenada",
                'GL'=>"Grenlandia",
                'GE'=>"Gruzja",
                'GU'=>"Guam",
                'GY'=>"Gujana",
                'GF'=>"Gujana Francuska",
                'GP'=>"Gwadelupa",
                'GT'=>"Gwatemala",
                'GN'=>"Gwinea",
                'GW'=>"Gwinea Bissau",
                'GQ'=>"Guinea Równikowa",
                'HT'=>"Haiti",
                'HM'=>"Heard i wyspy McDonalda",
                'ES'=>"Hiszpania",
                'NL'=>"Holandia",
                'HN'=>"Honduras",
                'HK'=>"Hongkong",
                'IN'=>"Indie",
                'ID'=>"Indonezia",
                'IQ'=>"Irak",
                'IR'=>"Iran",
                'IE'=>"Irlandia",
                'IS'=>"Islandia",
                'IL'=>"Izrael",
                'JM'=>"Jamajka",
                'JP'=>"Japonia",
                'YE'=>"Jemen",
                'JO'=>"Jordania",
                'KY'=>"Kajmany",
                'KH'=>"Kambod¿a",
                'CM'=>"Kamerun",
                'CA'=>"Kanada",
                'QA'=>"Katar",
                'KZ'=>"Kazachstan",
                'KE'=>"Kenia",
                'KI'=>"Kiribati",
                'CO'=>"Kolumbia",
                'KM'=>"Komory",
                'CG'=>"Kongo",
                'CD'=>"Kongo (d. Zair)",
                'KR'=>"Korea Po³udniowa",
                'KP'=>"Korea Pó³nocna",
                'CR'=>"Kostaryka",
                'CU'=>"Kuba",
                'KW'=>"Kuwejt",
                'KG'=>"Kyrgystan",
                'LA'=>"Laos",
                'LS'=>"Lesotho",
                'LB'=>"Liban",
                'LR'=>"Liberia",
                'LY'=>"Libia",
                'LI'=>"Liechtenstein",
                'LT'=>"Litwa",
                'LU'=>"Luksemburg",
                'LV'=>"£otwa",
                'MK'=>"Macedonia",
                'MG'=>"Madagaskar",
                'YT'=>"Majotta",
                'MO'=>"Makao",
                'MW'=>"Malawi",
                'MV'=>"Malediwy",
                'MY'=>"Malezja",
                'ML'=>"Mali",
                'MT'=>"Malta",
                'MA'=>"Maroko",
                'MQ'=>"Martynika",
                'MR'=>"Mauretania",
                'MU'=>"Mauritius",
                'MP'=>"Mariany Pó³nocne",
                'MX'=>"Meksyk",
                'FM'=>"Mikronezja",
                'UM'=>"Minor (Usa)",
                'MD'=>"Moldawia",
                'MC'=>"Monako",
                'MN'=>"Mongolia",
                'MS'=>"Montserrat",
                'MZ'=>"Mozambik",
                'MM'=>"Myanmar (Birma)",
                'NA'=>"Namibia",
                'NR'=>"Nauru",
                'NP'=>"Nepal",
                'DE'=>"Niemcy",
                'NE'=>"Niger",
                'NG'=>"Nigeria",
                'NI'=>"Nikaragua",
                'NU'=>"Niue",
                'NO'=>"Norwegia",
                'NC'=>"Nowa Kaledonia",
                'NZ'=>"Nowa Zelandia",
                'OM'=>"Oman",
                'PK'=>"Pakistan",
                'PW'=>"Palau",
                'PA'=>"Panama",
                'PG'=>"Papua Nowa Gwinea",
                'PY'=>"Paragwaj",
                'PE'=>"Peru",
                'PN'=>"Pitcairn",
                'PF'=>"Polinezja Francuska",
                'PL'=>"Polska",
                'GS'=>"Po³udniowa Georgia i p³d wyspy Sandwich",
                'PT'=>"Portugalia",
                'PR'=>"Portoryko",
                'ZA'=>"Rep. Po³ud. Afryki (RPA)",
                'CF'=>"Rep. ¦rodk. Afrykañska",
                'RE'=>"Reunion",
                'RU'=>"Rosja",
                'RO'=>"Rumunia",
                'RW'=>"Ruanda",
                'EH'=>"Sahara Zachodnia",
                'KN'=>"St.Kitts i Nevis",
                'PM'=>"St.Pierre i Miquelon",
                'VC'=>"St.Vincent i Grenadyny",
                'SV'=>"Salwador",
                'AS'=>"Samoa Amerykañskie",
                'WS'=>"Samoa",
                'SM'=>"San Marino",
                'SN'=>"Senegal",
                'CS'=>"Serbia i Czarnogóra",
                'SC'=>"Seszele",
                'SL'=>"Sierra Leone",
                'SG'=>"Singapur",
                'SK'=>"S³owacja",
                'SI'=>"Slowenia",
                'SO'=>"Somalia",
                'LK'=>"Sri Lanka",
                'US'=>"Stany Zjednoczone Ameryki",
                'SD'=>"Sudan",
                'SR'=>"Surinam",
                'SZ'=>"Suazi",
                'SY'=>"Syria",
                'SE'=>"Szwecja",
                'CH'=>"Szwajcaria",
                'SH'=>"¦wiêta Helena",
                'LC'=>"Swiêta £ucja",
                'TJ'=>"Tad¿ykistan",
                'TH'=>"Tajlandia",
                'TW'=>"Tajwan",
                'TZ'=>"Tanzania",
                'TG'=>"Togo",
                'TK'=>"Tokelau",
                'TT'=>"Trinidad i Tobago",
                'TO'=>"Tonga",
                'TN'=>"Tunezja",
                'TR'=>"Turcja",
                'TM'=>"Turkmenistan",
                'TC'=>"Turks i Caicos",
                'TV'=>"Tuvalu",
                'UG'=>"Uganda",
                'UA'=>"Ukraina",
                'UY'=>"Urugwaj",
                'UZ'=>"Uzbekistan",
                'VU'=>"Vanuatu",
                'WF'=>"Wallis i Futuna ",
                'VA'=>"Watykan",
                'VE'=>"Wenezuela",
                'HU'=>"Wêgry",
                'GB'=>"Wielka Brytania",
                'VN'=>"Wietnam",
                'IT'=>"W³ochy",
                'TP'=>"Wschodni Timor",
                'CI'=>"Wybrze¿e Ko¶ci S³oniowej",
                'BV'=>"Wyspa Bouveta",
                'CX'=>"Wyspa Bo¿ego Narodzenia",
                'CK'=>"Wyspy Cooka",
                'VI'=>"Wyspy Dziewicze (USA)",
                'VG'=>"Wyspy Dziewicze (Brytyjskie)",
                'CC'=>"Wyspy Kokosowe",
                'MH'=>"Wyspy Marshala",
                'FO'=>"Wyspy Salomona",
                'ST'=>"Wyspy ¦w.Tomasza i Ksi±¿êce",
                'CV'=>"Zielony Przyl±dek",
                'ZM'=>"Zambia",
                'ZW'=>"Zimbabwe",
                'AE'=>"Zjednoczone Emiraty Arabskie",
                'NT'=>"Neutralna strefa",
                );
	var $langs_symbols=array(
                '0'=>"pl",
                '1'=>"en",
                '2'=>"de",
                '3'=>"cz",
                '4'=>"ru",
                );
	var $langs_names=array(
                '0'=>"Polski",
                '1'=>"English",
                '2'=>"Deutsch",
                '3'=>"Cestina",
                '4'=>"Russkij",
                );
	var $langs_active=array(
                '0'=>"1",
                '1'=>"1",
                '2'=>"1",
                '3'=>"1",
                '4'=>"1",
                );
	var $langs_encoding=array(
                '0'=>"052|iso-8859-2",
                '1'=>"018|iso-8859-1",
                '2'=>"031|iso-8859-1",
                '3'=>"015|iso-8859-2",
                '4'=>"000|utf-8",
                );
	var $users_online="1";
	var $unit="kg";
	var $id_shop="0";
	var $pay_method=array(
                '1'=>"Za zaliczeniem",
                '3'=>"PolCard",
                '11'=>"Przelew",
                '12'=>"Przelewy24",
                '101'=>"PayPal",
                );
	var $ssl="0";
	var $catalog_mode_options=array(
                'currency'=>"0",
                'users'=>"0",
                'newsletter'=>"0",
                'newsedit'=>"0",
                'price'=>"0",
                );
	var $ranking1_max_length="5";
	var $ranking2_max_length="5";
	var $ranking1_enabled="1";
	var $ranking2_enabled="1";
	var $depository=array(
                'show_unavailable'=>"1",
                'general_min_num'=>"5",
                'update_num_on_action'=>"on_paid",
                'return_on_cancel'=>"1",
                'available_type_to_hide'=>"3",
                );
	var $basket_ext="0";
	var $basket_wishlist=array(
                'prod_ext_info'=>"0",
                );

} // end class MyConfig
$config = new MyConfig;
?>