<select class=form name="item[interia_category]" size="1"><option value="default">----wybierz----
<option  value="84">Dom i ogród/Wyposa¿enie domu i dekoracja/Szk³o, ceramika</option>
<option  value="85">Dom i ogród/Wyposa¿enie domu i dekoracja/Glazura terakota</option>
<option  value="87">Dom i ogród/Wyposa¿enie domu i dekoracja/Karnisze</option>
<option  value="88">Dom i ogród/Wyposa¿enie domu i dekoracja/Koce i ko³dry</option>
<option  value="89">Dom i ogród/Wyposa¿enie domu i dekoracja/Okleiny</option>
<option  value="90">Dom i ogród/Wyposa¿enie domu i dekoracja/Pasmanteria</option>
<option  value="91">Dom i ogród/Wyposa¿enie domu i dekoracja/Poduszki</option>
<option  value="92">Dom i ogród/Wyposa¿enie domu i dekoracja/Po¶ciel</option>
<option  value="93">Dom i ogród/Wyposa¿enie domu i dekoracja/Rêczniki</option>
<option  value="94">Dom i ogród/Wyposa¿enie domu i dekoracja/Szklo krysztaly</option>
<option  value="95">Dom i ogród/Wyposa¿enie domu i dekoracja/¦wiece</option>
<option  value="96">Dom i ogród/Wyposa¿enie domu i dekoracja/Tapety</option>
<option  value="97">Dom i ogród/Wyposa¿enie domu i dekoracja/Tkaniny i materialy</option>
<option  value="98">Dom i ogród/Wyposa¿enie domu i dekoracja/Wiklina</option>
<option  value="99">Dom i ogród/Wyposa¿enie domu i dekoracja/Wyk³adziny i dywany</option>
<option  value="100">Dom i ogród/Wyposa¿enie domu i dekoracja/Zas³ony i firany</option>
<option  value="101">Dom i ogród/Wyposa¿enie domu i dekoracja/Zegary</option>
<option  value="102">Dom i ogród/Wyposa¿enie domu i dekoracja/¯aluzje</option>
<option  value="2452">Dom i ogród/Wyposa¿enie domu i dekoracja/O¶wietlenie/Dyskotekowe</option>
<option  value="1661">Dom i ogród/Wyposa¿enie domu i dekoracja/Swieczniki</option>
<option  value="1662">Dom i ogród/Wyposa¿enie domu i dekoracja/Zastawa sto³owa - inne</option>
<option  value="1663">Dom i ogród/Wyposa¿enie domu i dekoracja/Wazony</option>
<option  value="1664">Dom i ogród/Wyposa¿enie domu i dekoracja/Do kawy i herbaty</option>
<option  value="1665">Dom i ogród/Wyposa¿enie domu i dekoracja/Akcesoria kominkowe</option>
<option  value="1666">Dom i ogród/Wyposa¿enie domu i dekoracja/Zastawa - szk³o (do alkoholi)</option>
<option  value="1667">Dom i ogród/Wyposa¿enie domu i dekoracja/Talerze i patery</option>
<option  value="1668">Dom i ogród/Wyposa¿enie domu i dekoracja/Misy i tace</option>
<option  value="1669">Dom i ogród/Wyposa¿enie domu i dekoracja/Popielnice</option>
<option  value="1670">Dom i ogród/Wyposa¿enie domu i dekoracja/Cukiernice</option>
<option  value="1671">Dom i ogród/Wyposa¿enie domu i dekoracja/Serwetniki</option>
<option  value="107">Dom i ogród/Alarmy/Przeciwpozarowe ognioodporne</option>
<option  value="108">Dom i ogród/Alarmy/Sejfy i kasy pancerne</option>
<option  value="109">Dom i ogród/Alarmy/Zamki</option>
<option  value="1672">Dom i ogród/Alarmy/Domofony</option>
<option  value="1673">Dom i ogród/Alarmy/Kontrola dostepu</option>
<option  value="134">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Grzejniki olejowe</option>
<option  value="135">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Inne ogrzewanie</option>
<option  value="137">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Instalacje grzewcze co</option>
<option  value="138">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Ogrzewanie elektryczne</option>
<option  value="139">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Klimatyzatory</option>
<option  value="140">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Nawil¿acze powietrza</option>
<option  value="141">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Ogrzewanie ³azienkowe</option>
<option  value="142">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Termowentylatory</option>
<option  value="143">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Wentylatory</option>
<option  value="1674">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Ogrzewanie gazowe</option>
<option  value="1675">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Ogrzewanie halogenowe</option>
<option  value="1676">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Piece akumulacyjne</option>
<option  value="1677">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Piece, kot³y C.O.</option>
<option  value="1678">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Pogrzewacze wody</option>
<option  value="1680">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Pojemno¶ciowe podgrzewacze wody</option>
<option  value="1681">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Butle gazowe i akcesoria</option>
<option  value="1682">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Kratki wentylacyjne</option>
<option  value="1683">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Piece nadumchowe olejowe</option>
<option  value="1684">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Piece nadmuchowe gazowe</option>
<option  value="1685">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Nagrzewnice powietrza</option>
<option  value="3397">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Kurtyny powietrzne</option>
<option  value="3400">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Sterowniki temperatury</option>
<option  value="3401">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Ogrzewacze powietrza</option>
<option  value="3402">Dom i ogród/Ogrzewanie wentylacja klimatyzacja/Suszarki ³azienkowe</option>
<option  value="144">Dom i ogród/Okna, drzwi i ramy</option>
<option  value="155">Dom i ogród/Pod³ogi, schody, boazerie</option>
<option  value="160">Dom i ogród/Warsztat/Frezarki</option>
<option  value="162">Dom i ogród/Warsztat/Materia³y</option>
<option  value="163">Dom i ogród/Warsztat/M³otowiertarki</option>
<option  value="164">Dom i ogród/Warsztat/M³oty udarowe</option>
<option  value="165">Dom i ogród/Warsztat/Narzêdzia rêczne</option>
<option  value="166">Dom i ogród/Warsztat/Narzêdzia ogrodowe</option>
<option  value="167">Dom i ogród/Warsztat/Opalarki</option>
<option  value="168">Dom i ogród/Warsztat/Pi³y, pilarki</option>
<option  value="171">Dom i ogród/Warsztat/Szlifierki</option>
<option  value="173">Dom i ogród/Warsztat/Wiertarki</option>
<option  value="174">Dom i ogród/Warsztat/Wkrêtaki akumulatorowe</option>
<option  value="175">Dom i ogród/Warsztat/Wyrzynarki</option>
<option  value="3078">Dom i ogród/Warsztat/Wyposa¿enie dodatkowe</option>
<option  value="3079">Dom i ogród/Warsztat/Urz±dzenia profesjonalne</option>
<option  value="80">Dom i ogród/Wyposa¿enie kuchni/Materia³y(folie,papiery itd.)</option>
<option  value="81">Dom i ogród/Wyposa¿enie kuchni/Sztuæce</option>
<option  value="82">Dom i ogród/Wyposa¿enie kuchni/Termosy</option>
<option  value="126">Dom i ogród/Wyposa¿enie kuchni/Garnki i patelnie</option>
<option  value="178">Dom i ogród/Wyposa¿enie kuchni/Dodatki</option>
<option  value="179">Dom i ogród/Wyposa¿enie kuchni/Formy do pieczenia</option>
<option  value="1687">Dom i ogród/Wyposa¿enie kuchni/Serwisy obiadowe i deserowe</option>
<option  value="1688">Dom i ogród/Wyposa¿enie kuchni/No¿e kuchenne</option>
<option  value="1689">Dom i ogród/Wyposa¿enie kuchni/Pojemniki (na ¿ywno¶?, przyprawy itd)</option>
<option  value="1690">Dom i ogród/Wyposa¿enie kuchni/Baterie kuchenne</option>
<option  value="204">Dom i ogród/Baseny</option>
<option  value="3081">Dom i ogród/Stacje pogodowe/Barometry</option>
<option  value="3082">Dom i ogród/Stacje pogodowe/Higrometry</option>
<option  value="3083">Dom i ogród/Stacje pogodowe/Mierniki wiatru</option>
<option  value="206">Dom i ogród/Kominki</option>
<option  value="208">Dom i ogród/£azienka/Armatura</option>
<option  value="209">Dom i ogród/£azienka/Ceramika ³azienkowa</option>
<option  value="210">Dom i ogród/£azienka/Glazura i terakota</option>
<option  value="212">Dom i ogród/£azienka/Panele natryskowe</option>
<option  value="1691">Dom i ogród/£azienka/Zlewozmywaki</option>
<option  value="1694">Dom i ogród/£azienka/Baterie umywalkowe</option>
<option  value="1695">Dom i ogród/£azienka/Baterie natryskowe</option>
<option  value="1696">Dom i ogród/£azienka/Baterie bidetowe</option>
<option  value="1697">Dom i ogród/£azienka/Baterie wannowo-natryskowe</option>
<option  value="1698">Dom i ogród/£azienka/Baterie akcesoria</option>
<option  value="1699">Dom i ogród/£azienka/Pisuary</option>
<option  value="1700">Dom i ogród/£azienka/Bidety</option>
<option  value="1705">Dom i ogród/£azienka/WC/Deski sedesowe</option>
<option  value="1706">Dom i ogród/£azienka/WC/Miski podwieszane</option>
<option  value="1707">Dom i ogród/£azienka/Wanny i kabiny</option>
<option  value="1714">Dom i ogród/£azienka/Kabiny prysznicowe</option>
<option  value="1719">Dom i ogród/£azienka/Umywalki</option>
<option  value="1724">Dom i ogród/£azienka/Instalacje podtynkowe</option>
<option  value="3313">Dom i ogród/£azienka/Baterie zlewozmykakowe</option>
<option  value="217">Dom i ogród/Materia³y i sprzêt budowlany/Dachy, dachówki, pokrycia dachowe</option>
<option  value="218">Dom i ogród/Materia³y i sprzêt budowlany/Farby, kleje, elewacje</option>
<option  value="221">Dom i ogród/Materia³y i sprzêt budowlany/Izolacje, ocieplenia</option>
<option  value="223">Dom i ogród/Materia³y i sprzêt budowlany/Instalacje wodno-kanalizacyjne</option>
<option  value="1762">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Inne wyroby</option>
<option  value="1763">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Materia³y stropowe</option>
<option  value="1764">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Materia³y ¶cienne</option>
<option  value="1765">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Zaprawy</option>
<option  value="1766">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Wyroby elewacyjne</option>
<option  value="1767">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Wyroby konstrukcyjne</option>
<option  value="1768">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Belki</option>
<option  value="1769">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Pustaki kominowe</option>
<option  value="1770">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/¦ciany</option>
<option  value="3315">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y ¶cienne i stropowe/Stropy</option>
<option  value="3411">Dom i ogród/Materia³y i sprzêt budowlany/Materia³y wykoñczeniowe/Ogrzewanie pod³ogowe</option>
<option  value="127">Dom i ogród/Ogród/Rze¼by i ornamenty</option>
<option  value="129">Dom i ogród/Ogród/Staw/Filtry</option>
<option  value="130">Dom i ogród/Ogród/Staw/Pompy</option>
<option  value="1730">Dom i ogród/Ogród/Staw/Formy do stawów</option>
<option  value="131">Dom i ogród/Ogród/¦rodki na szkodniki</option>
<option  value="132">Dom i ogród/Ogród/Ziemia i dodatki</option>
<option  value="177">Dom i ogród/Ogród/Ro¶liny</option>
<option  value="1731">Dom i ogród/Ogród/Ogrodzenia bramy/Ogrodzenia</option>
<option  value="1732">Dom i ogród/Ogród/Ogrodzenia bramy/Bramy</option>
<option  value="232">Dom i ogród/Ogród/Narzêdzia ogrodnicze</option>
<option  value="233">Dom i ogród/Ogród/Nasiona i bulwy</option>
<option  value="234">Dom i ogród/Ogród/Place zabaw</option>
<option  value="1733">Dom i ogród/Ogród/Kosiarki</option>
<option  value="1737">Dom i ogród/Ogród/Traktorki ogrodowe</option>
<option  value="1738">Dom i ogród/Ogród/Podkaszarki, kosy</option>
<option  value="1740">Dom i ogród/Ogród/Zbieracze li¶ci</option>
<option  value="1741">Dom i ogród/Ogród/Odkurzacze do li¶ci</option>
<option  value="1742">Dom i ogród/Ogród/Rozdrabniacze ga³êzi</option>
<option  value="1743">Dom i ogród/Ogród/No¿yce do ¿ywop³otu</option>
<option  value="1744">Dom i ogród/Ogród/Pilarki ³añcuchowe</option>
<option  value="1745">Dom i ogród/Ogród/Od¶nie¿arki</option>
<option  value="1746">Dom i ogród/Ogród/Glebogryzarki</option>
<option  value="1747">Dom i ogród/Ogród/Aeratory</option>
<option  value="3090">Dom i ogród/Ogród/Rekreacja</option>
<option  value="3091">Dom i ogród/Ogród/Pompy do stawów</option>
<option  value="1749">Dom i ogród/Klimatyzacja/Klimatyzatory na¶cienne pojedyncze</option>
<option  value="1750">Dom i ogród/Klimatyzacja/Klimatyzatory na¶cienne multisplity</option>
<option  value="1751">Dom i ogród/Klimatyzacja/Klimatyzatory na¶cienne bez jednostki zewnêtrznej</option>
<option  value="1752">Dom i ogród/Klimatyzacja/Klimatyzatory okienne</option>
<option  value="1753">Dom i ogród/Klimatyzacja/Klimatyzatory przypod³ogowo - sufitowe</option>
<option  value="1754">Dom i ogród/Klimatyzacja/Klimatyzatory kana³owe</option>
<option  value="1755">Dom i ogród/Klimatyzacja/Klimatyzatory kasetonowe</option>
<option  value="1756">Dom i ogród/Klimatyzacja/Klimatyzatory przeno¶ne</option>
<option  value="1757">Dom i ogród/Klimatyzacja/Pompy do odprowadzania skroplin</option>
<option  value="1758">Dom i ogród/Klimatyzacja/Osuszacze</option>
<option  value="1760">Dom i ogród/Buduj dom/Bramy i systemy ogrodzeniowe</option>
<option  value="1773">Dom i ogród/Buduj dom/Chemia budowlana/Zaprawy budowlane</option>
<option  value="1774">Dom i ogród/Buduj dom/Chemia budowlana/Materia³y do przyklejania styropianu i uk³adania tapet</option>
<option  value="1775">Dom i ogród/Buduj dom/Chemia budowlana/Materia³y do uk³adania ok³adzin ceramicznych</option>
<option  value="1776">Dom i ogród/Buduj dom/Chemia budowlana/Materia³y gruntuj±ce czyszcz±ce i zabezpieczaj±ce</option>
<option  value="1777">Dom i ogród/Buduj dom/Chemia budowlana/Materia³y izoluj±ce i uszczelniaj±ce</option>
<option  value="1778">Dom i ogród/Buduj dom/Chemia budowlana/Posadzki i podk³ady samopoziomuj±ce</option>
<option  value="1779">Dom i ogród/Buduj dom/Chemia budowlana/Tynki szlachetne i systemy dociepleñ</option>
<option  value="1780">Dom i ogród/Buduj dom/Chemia budowlana/Wyroby gipsowe</option>
<option  value="1781">Dom i ogród/Buduj dom/Chemia budowlana/Farby elewacyjne</option>
<option  value="1782">Dom i ogród/Buduj dom/Chemia budowlana/Preparaty gruntuj±ce</option>
<option  value="1783">Dom i ogród/Buduj dom/Chemia budowlana/Izolacje i wylewki</option>
<option  value="1784">Dom i ogród/Buduj dom/Chemia budowlana/P³yny i ¶rodki</option>
<option  value="1785">Dom i ogród/Buduj dom/Chemia budowlana/Spoiny i silikony</option>
<option  value="1786">Dom i ogród/Buduj dom/Chemia budowlana/Suche zaprawy murarsko-tynkarskie</option>
<option  value="1787">Dom i ogród/Buduj dom/Chemia budowlana/Tynki</option>
<option  value="1790">Dom i ogród/Buduj dom/Chemia budowlana/Kleje i zaprawy</option>
<option  value="1791">Dom i ogród/Buduj dom/Chemia budowlana/Podk³ady pod³ogowe</option>
<option  value="1792">Dom i ogród/Buduj dom/Chemia budowlana/Zaprawy mieszanki</option>
<option  value="1794">Dom i ogród/Buduj dom/Chemia budowlana/Zaprawy klej±ce i spoiny do p³ytek</option>
<option  value="1795">Dom i ogród/Buduj dom/Chemia budowlana/Zaprawy murarskie i fugi</option>
<option  value="3316">Dom i ogród/Buduj dom/Chemia budowlana/Gipsy</option>
<option  value="3317">Dom i ogród/Buduj dom/Chemia budowlana/Grunty</option>
<option  value="1810">Dom i ogród/Buduj dom/Materia³y ¶cienne gazobetonowe i silikatowe</option>
<option  value="1821">Dom i ogród/Buduj dom/Materia³y izolacyjne/Elementy uzupe³niaj±ce</option>
<option  value="1822">Dom i ogród/Buduj dom/Materia³y izolacyjne/Folie</option>
<option  value="1824">Dom i ogród/Buduj dom/Materia³y izolacyjne/Materia³y pokryciowe</option>
<option  value="1825">Dom i ogród/Buduj dom/Materia³y izolacyjne/Pokrycia monta¿owe</option>
<option  value="1826">Dom i ogród/Buduj dom/Materia³y izolacyjne/Izolacje wodochronne</option>
<option  value="1827">Dom i ogród/Buduj dom/Materia³y izolacyjne/Folie paroizolacyjne</option>
<option  value="1828">Dom i ogród/Buduj dom/Materia³y izolacyjne/Folie wiatroizolacyjne</option>
<option  value="1829">Dom i ogród/Buduj dom/Materia³y izolacyjne/Izolacje termiczne</option>
<option  value="1830">Dom i ogród/Buduj dom/Pod³ogi drewniane i panele pod³ogowe</option>
<option  value="1832">Dom i ogród/Buduj dom/Pokrycia dachowe/Dachówki i elementy uzupe³niaj±ce</option>
<option  value="1833">Dom i ogród/Buduj dom/Pokrycia dachowe/Folie dachowe</option>
<option  value="1834">Dom i ogród/Buduj dom/Pokrycia dachowe/P³ytki euronit</option>
<option  value="1835">Dom i ogród/Buduj dom/Pokrycia dachowe/P³ytki struktonit</option>
<option  value="1837">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Okna PCV</option>
<option  value="1838">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Drzwi zewnêtrzne</option>
<option  value="1840">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Okna drewniane</option>
<option  value="1841">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/O¶cie¿nice</option>
<option  value="1842">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Klamki</option>
<option  value="1843">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Okna i drzwi balkonowe</option>
<option  value="1844">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Drzwi</option>
<option  value="3319">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Skrzyd³a drzwiowe</option>
<option  value="3320">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Drzwi przesuwane</option>
<option  value="3321">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/Okna do poddaszy</option>
<option  value="3322">Dom i ogród/Buduj dom/Stolarka okienna i drzwiowa/W³azy dachowe</option>
<option  value="1847">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Wylewki</option>
<option  value="1848">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/P³yty kartonowo-gipsowe</option>
<option  value="1849">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/P³yty cementowe, p³yty gipsowo-w³óknowe</option>
<option  value="1850">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/P³yty ogniowe, p³yty akustyczne</option>
<option  value="1851">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Sufity akustyczne</option>
<option  value="1852">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Kleje i masy szpachlowe</option>
<option  value="1853">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/¦rodki gruntuj±ce</option>
<option  value="1854">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Profile</option>
<option  value="1855">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Szyny ochronne</option>
<option  value="1856">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Dodatki monta¿owe</option>
<option  value="1857">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Klapy rewizyjne</option>
<option  value="1858">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Technika zamocowañ</option>
<option  value="1859">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Stojaki sanitarne</option>
<option  value="1860">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Systemy drzwi przesuwnych i o¶cie¿nice</option>
<option  value="3405">Dom i ogród/Buduj dom/Sucha zabudowa wnêtrz/Masy</option>
<option  value="1862">Dom i ogród/Buduj dom/Maszyny budowlane i narzêdzia/Narzêdzia</option>
<option  value="3398">Dom i ogród/Buduj dom/Maszyny budowlane i narzêdzia/Maszyny tynkarskie</option>
<option  value="3414">Dom i ogród/Obrazy, plakaty, ramy/Abstrakcje</option>
<option  value="3416">Dom i ogród/Obrazy, plakaty, ramy/Filmowe</option>
<option  value="3417">Dom i ogród/Obrazy, plakaty, ramy/Mapy</option>
<option  value="3419">Dom i ogród/Obrazy, plakaty, ramy/Widoki</option>
<option  value="3420">Dom i ogród/Obrazy, plakaty, ramy/Akty</option>
<option  value="3421">Dom i ogród/Obrazy, plakaty, ramy/Dziewczyny</option>
<option  value="3422">Dom i ogród/Obrazy, plakaty, ramy/Humor</option>
<option  value="3423">Dom i ogród/Obrazy, plakaty, ramy/Martwa natura</option>
<option  value="3424">Dom i ogród/Obrazy, plakaty, ramy/Osobisto¶ci</option>
<option  value="3426">Dom i ogród/Obrazy, plakaty, ramy/Antyczne</option>
<option  value="3428">Dom i ogród/Obrazy, plakaty, ramy/Kwiaty</option>
<option  value="3429">Dom i ogród/Obrazy, plakaty, ramy/Marynistyka</option>
<option  value="3430">Dom i ogród/Obrazy, plakaty, ramy/Pejza¿e</option>
<option  value="3431">Dom i ogród/Obrazy, plakaty, ramy/Czarno-bia³e</option>
<option  value="3432">Dom i ogród/Obrazy, plakaty, ramy/Figuralne</option>
<option  value="3435">Dom i ogród/Obrazy, plakaty, ramy/Ramy</option>
<option  value="29">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Antyperspiranty</option>
<option  value="30">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Balsamy</option>
<option  value="31">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Mydla</option>
<option  value="32">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Peelingi</option>
<option  value="33">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Preparaty ujedrniajace</option>
<option  value="34">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Rozne</option>
<option  value="1634">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/¯ele pod prysznic</option>
<option  value="3051">Uroda i zdrowie/Kosmetyki damskie/Do cia³a/Kremy do stóp</option>
<option  value="36">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Emulsje</option>
<option  value="37">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Kremy</option>
<option  value="38">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Maseczki</option>
<option  value="39">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Toniki i mleczka</option>
<option  value="41">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Pod oczy</option>
<option  value="42">Uroda i zdrowie/Kosmetyki damskie/Do twarzy/Toniki</option>
<option  value="44">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Akcesoria</option>
<option  value="45">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Farby</option>
<option  value="46">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Lakiery</option>
<option  value="47">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Odzywki</option>
<option  value="48">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Pianki</option>
<option  value="49">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Inne</option>
<option  value="50">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Szampony</option>
<option  value="51">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Szampony koloryzujace</option>
<option  value="52">Uroda i zdrowie/Kosmetyki damskie/Do w³osów/Zele</option>
<option  value="55">Uroda i zdrowie/Kosmetyki damskie/Higiena intymna/Plyny do higieny intymnej</option>
<option  value="56">Uroda i zdrowie/Kosmetyki damskie/Higiena intymna/Podpaski</option>
<option  value="57">Uroda i zdrowie/Kosmetyki damskie/Higiena intymna/Tampony</option>
<option  value="58">Uroda i zdrowie/Kosmetyki damskie/Higiena intymna/Wkladki higieniczne</option>
<option  value="3058">Uroda i zdrowie/Kosmetyki damskie/Pomadki</option>
<option  value="63">Uroda i zdrowie/Kosmetyki dla niemowl±t/Myd³a</option>
<option  value="64">Uroda i zdrowie/Kosmetyki dla niemowl±t/Oliwki</option>
<option  value="65">Uroda i zdrowie/Kosmetyki dla niemowl±t/P³yny i ¿ele do k±pieli</option>
<option  value="67">Uroda i zdrowie/Kosmetyki dla niemowl±t/Zasypki</option>
<option  value="69">Uroda i zdrowie/Kosmetyki mêskie/Do golenia</option>
<option  value="70">Uroda i zdrowie/Kosmetyki mêskie/Balsamy po goleniu</option>
<option  value="71">Uroda i zdrowie/Kosmetyki mêskie/Dezodoranty</option>
<option  value="75">Uroda i zdrowie/Kosmetyki mêskie/Wody po goleniu</option>
<option  value="77">Uroda i zdrowie/Kosmetyki mêskie/Do k±pieli</option>
<option  value="3065">Uroda i zdrowie/Kosmetyki mêskie/Zestawy dla Panów</option>
<option  value="110">Uroda i zdrowie/¦rodki czyszcz±ce</option>
<option  value="610">Uroda i zdrowie/Kosmetyki uniwersalne/Akcesoria do w³osów</option>
<option  value="611">Uroda i zdrowie/Kosmetyki uniwersalne/Bagietki kosmetyczne</option>
<option  value="612">Uroda i zdrowie/Kosmetyki uniwersalne/Do opalania</option>
<option  value="613">Uroda i zdrowie/Kosmetyki uniwersalne/Farby do w³osów</option>
<option  value="614">Uroda i zdrowie/Kosmetyki uniwersalne/G±bki do k±pieli</option>
<option  value="617">Uroda i zdrowie/Kosmetyki uniwersalne/Mleczka</option>
<option  value="619">Uroda i zdrowie/Kosmetyki uniwersalne/Od¿ywki do w³osów</option>
<option  value="620">Uroda i zdrowie/Kosmetyki uniwersalne/Pasty do zêbów</option>
<option  value="621">Uroda i zdrowie/Kosmetyki uniwersalne/Pianki do w³osów</option>
<option  value="622">Uroda i zdrowie/Kosmetyki uniwersalne/P³atki kosmetyczne</option>
<option  value="623">Uroda i zdrowie/Kosmetyki uniwersalne/P³yny do k±pieli</option>
<option  value="625">Uroda i zdrowie/Kosmetyki uniwersalne/Szczoteczki do zêbów</option>
<option  value="627">Uroda i zdrowie/Kosmetyki uniwersalne/¯ele do w³osów</option>
<option  value="1638">Uroda i zdrowie/Kosmetyki uniwersalne/Pielêgnacja nóg</option>
<option  value="1639">Uroda i zdrowie/Kosmetyki uniwersalne/Pielêgnacja stóp</option>
<option  value="1640">Uroda i zdrowie/Kosmetyki uniwersalne/Sole do k±pieli</option>
<option  value="1641">Uroda i zdrowie/Kosmetyki uniwersalne/¯ele do k±pieli</option>
<option  value="1642">Uroda i zdrowie/Kosmetyki uniwersalne/Olejki do k±pieli</option>
<option  value="1643">Uroda i zdrowie/Kosmetyki uniwersalne/Talki do cia³a</option>
<option  value="630">Uroda i zdrowie/Makija¿/Oczy</option>
<option  value="632">Uroda i zdrowie/Makija¿/Twarz</option>
<option  value="633">Uroda i zdrowie/Makija¿/Usta</option>
<option  value="636">Uroda i zdrowie/Perfumy i zapachy/Perfumy damskie</option>
<option  value="637">Uroda i zdrowie/Perfumy i zapachy/Perfumy mêskie</option>
<option  value="638">Uroda i zdrowie/Perfumy i zapachy/Perfumy unisex</option>
<option  value="639">Uroda i zdrowie/Perfumy i zapachy/Wody perfumowane</option>
<option  value="640">Uroda i zdrowie/Perfumy i zapachy/Wody toaletowe mêskie</option>
<option  value="641">Uroda i zdrowie/Perfumy i zapachy/Wody toaletowe unisex</option>
<option  value="1644">Uroda i zdrowie/Perfumy i zapachy/Wody toaletowe damskie</option>
<option  value="1646">Uroda i zdrowie/Perfumy i zapachy/Inne zapachy</option>
<option  value="1647">Uroda i zdrowie/Perfumy i zapachy/Miniaturki damskie</option>
<option  value="1648">Uroda i zdrowie/Perfumy i zapachy/Miniaturki mêskie</option>
<option  value="1593">Uroda i zdrowie/Antykoncepcja</option>
<option  value="1595">Uroda i zdrowie/Apteka - alternatywna/Homeopatyczne</option>
<option  value="1596">Uroda i zdrowie/Apteka - alternatywna/Produkty do aromaterapii</option>
<option  value="1597">Uroda i zdrowie/Apteka - alternatywna/Zio³a</option>
<option  value="2414">Uroda i zdrowie/Apteka - alternatywna/Dla alergików</option>
<option  value="2415">Uroda i zdrowie/Apteka - alternatywna/Witaminy i minera³y</option>
<option  value="2416">Uroda i zdrowie/Apteka - alternatywna/Napoje aloesowe</option>
<option  value="2417">Uroda i zdrowie/Apteka - alternatywna/Produkty pszczele</option>
<option  value="2418">Uroda i zdrowie/Apteka - alternatywna/Preparaty od¿ywcze</option>
<option  value="1598">Uroda i zdrowie/Apteka - Antyseptyczne i dezynfekcyjne</option>
<option  value="1600">Uroda i zdrowie/Apteka - leki/Dermatologiczne</option>
<option  value="1602">Uroda i zdrowie/Apteka - leki/Katar, kaszel, przeziêbienie</option>
<option  value="1603">Uroda i zdrowie/Apteka - leki/Minera³y i witaminy</option>
<option  value="1604">Uroda i zdrowie/Apteka - leki/Na trawienie</option>
<option  value="1605">Uroda i zdrowie/Apteka - leki/Od¿ywki</option>
<option  value="1606">Uroda i zdrowie/Apteka - leki/Okulistyczne</option>
<option  value="1607">Uroda i zdrowie/Apteka - leki/Preparaty wspomagaj±ce odchudzanie</option>
<option  value="1608">Uroda i zdrowie/Apteka - leki/Przeciwbólowe</option>
<option  value="1609">Uroda i zdrowie/Apteka - leki/Przeczyszczaj±ce</option>
<option  value="1610">Uroda i zdrowie/Apteka - leki/Serce</option>
<option  value="1611">Uroda i zdrowie/Apteka - leki/Stomatologiczne</option>
<option  value="1612">Uroda i zdrowie/Apteka - leki/Usypiaj±ce i uspokajaj±ce</option>
<option  value="1615">Uroda i zdrowie/Apteka - sprzêt/Aparaty do pomiaru ci¶nienia</option>
<option  value="1616">Uroda i zdrowie/Apteka - sprzêt/Do zastrzyków</option>
<option  value="1617">Uroda i zdrowie/Apteka - sprzêt/Inhalatory</option>
<option  value="1619">Uroda i zdrowie/Apteka - sprzêt/Przyrz±dy do masa¿u</option>
<option  value="1620">Uroda i zdrowie/Apteka - sprzêt/Przyrz±dy do poruszania siê</option>
<option  value="1621">Uroda i zdrowie/Apteka - sprzêt/Ratowniczy</option>
<option  value="1622">Uroda i zdrowie/Apteka - sprzêt/Sprzêt rehabilitacyjny</option>
<option  value="1623">Uroda i zdrowie/Apteka - sprzêt/Sprzêt ortopedyczny</option>
<option  value="1624">Uroda i zdrowie/Apteka - sprzêt/Stetoskopy</option>
<option  value="1626">Uroda i zdrowie/Apteka - sprzêt/Testy domowe</option>
<option  value="1627">Uroda i zdrowie/Apteka - sprzêt/Wyposa¿enie ³azienek</option>
<option  value="1628">Uroda i zdrowie/Apteka - ¶rodki opatrunkowe</option>
<option  value="1632">Uroda i zdrowie/Optyka/Okulary</option>
<option  value="1633">Uroda i zdrowie/Optyka/Soczewki</option>
<option  value="1650">Uroda i zdrowie/Dermokosmetyki/Preparaty z filtrem UV</option>
<option  value="1651">Uroda i zdrowie/Dermokosmetyki/Preparaty do cery wra¿liwej</option>
<option  value="1652">Uroda i zdrowie/Dermokosmetyki/Preparaty do cery dojrza³ej</option>
<option  value="1653">Uroda i zdrowie/Dermokosmetyki/Preparaty do cery t³ustej</option>
<option  value="1654">Uroda i zdrowie/Dermokosmetyki/Preparaty do cery suchej</option>
<option  value="1655">Uroda i zdrowie/Dermokosmetyki/Preparaty do cery naczynkowej</option>
<option  value="1656">Uroda i zdrowie/Dermokosmetyki/Preparaty do cia³a</option>
<option  value="1657">Uroda i zdrowie/Dermokosmetyki/Kremy pod oczy</option>
<option  value="2420">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Stomatologia</option>
<option  value="2421">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Dezynfekcja i Sterylizacja</option>
<option  value="2422">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Diagnostyka ultrasonograficzna</option>
<option  value="2423">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Drobny sprzêt medyczny</option>
<option  value="2424">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Fizykoterapia</option>
<option  value="2425">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Ginekologia i Po³o¿nictwo</option>
<option  value="2426">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Kardiologia</option>
<option  value="2427">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Laboratorium</option>
<option  value="2428">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Meble medyczne</option>
<option  value="2429">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Odzie¿ i obuwie medyczne</option>
<option  value="2430">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Ortopedia</option>
<option  value="2431">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Radiologia</option>
<option  value="2432">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Reanimacja i Pogotowie ratunkowe</option>
<option  value="2433">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Rehabilitacja</option>
<option  value="2434">Uroda i zdrowie/Sprzêt i aparatrura medyczna/Termoterapia</option>
<option  value="2435">Uroda i zdrowie/Jama ustna</option>
<option  value="3309">Uroda i zdrowie/Odchudzanie/Preparaty odchudzaj±ce</option>
<option  value="3310">Uroda i zdrowie/Odchudzanie/Preparaty wspomagaj±ce</option>
<option  value="3311">Uroda i zdrowie/Odchudzanie/Preparaty zio³owe</option>
<option  value="182">Dla zwierz±t/Ptaki/Klatki</option>
<option  value="183">Dla zwierz±t/Ptaki/Ksi±¿ki</option>
<option  value="184">Dla zwierz±t/Ptaki/Pokarmy</option>
<option  value="185">Dla zwierz±t/Ptaki/Smako³yki i witaminy</option>
<option  value="190">Dla zwierz±t/¯ó³wie/Preparaty</option>
<option  value="191">Dla zwierz±t/¯ó³wie/Terraria</option>
<option  value="248">Dla zwierz±t/Akwarystyka/Dekoracje</option>
<option  value="250">Dla zwierz±t/Akwarystyka/Grza³ki</option>
<option  value="252">Dla zwierz±t/Akwarystyka/Leki</option>
<option  value="253">Dla zwierz±t/Akwarystyka/Napowietrzanie</option>
<option  value="256">Dla zwierz±t/Akwarystyka/Chemia i preparaty</option>
<option  value="258">Dla zwierz±t/Akwarystyka/Testy wody</option>
<option  value="3092">Dla zwierz±t/Akwarystyka/Zestawy akwarystyczne</option>
<option  value="265">Dla zwierz±t/Gryzonie/¦rodki higieniczne</option>
<option  value="270">Dla zwierz±t/Kot/Kocie piaski</option>
<option  value="273">Dla zwierz±t/Kot/Preparaty ochronne</option>
<option  value="274">Dla zwierz±t/Kot/Smako³yki</option>
<option  value="275">Dla zwierz±t/Kot/Witaminy</option>
<option  value="230">Dla zwierz±t/Pies/Zabawki</option>
<option  value="279">Dla zwierz±t/Pies/Kagañce</option>
<option  value="280">Dla zwierz±t/Pies/Klatki i legowiska</option>
<option  value="283">Dla zwierz±t/Pies/Obro¿e</option>
<option  value="284">Dla zwierz±t/Pies/Pielêgnacja</option>
<option  value="288">Dla zwierz±t/Pies/Smycze</option>
<option  value="235">Dla dzieci/Pluszowe</option>
<option  value="242">Dla dzieci/Zestawy zabawek dla ch³opca</option>
<option  value="243">Dla dzieci/Zestawy dla ch³opców</option>
<option  value="244">Dla dzieci/Zestawy zabawek dla dziewczynki</option>
<option  value="245">Dla dzieci/Zestawy dla dziewczynek</option>
<option  value="302">Dla dzieci/Inne zabawki/Figurki</option>
<option  value="308">Dla dzieci/Klocki</option>
<option  value="311">Dla dzieci/Lalki i akcesoria/Lalki</option>
<option  value="1865">Dla dzieci/Lalki i akcesoria/Ubranka dla Lalek</option>
<option  value="3104">Dla dzieci/Lalki i akcesoria/Domki</option>
<option  value="3105">Dla dzieci/Lalki i akcesoria/Mebelki</option>
<option  value="313">Dla dzieci/Modelarstwo/Akcesoria do kolejek</option>
<option  value="314">Dla dzieci/Modelarstwo/Akcesoria do modeli</option>
<option  value="315">Dla dzieci/Modelarstwo/Inne modele</option>
<option  value="316">Dla dzieci/Modelarstwo/Kolejki</option>
<option  value="317">Dla dzieci/Modelarstwo/Modele do sklejania</option>
<option  value="318">Dla dzieci/Modelarstwo/Modele samochodów</option>
<option  value="324">Dla dzieci/Tekstylia</option>
<option  value="325">Dla dzieci/Tekstylia domowe</option>
<option  value="327">Dla dzieci/Wózki i foteliki samochodowe/Akcesoria do wózków</option>
<option  value="328">Dla dzieci/Wózki i foteliki samochodowe/Chodziki</option>
<option  value="329">Dla dzieci/Wózki i foteliki samochodowe/Foteliki samochodowe i akcesoria</option>
<option  value="332">Dla dzieci/Wózki i foteliki samochodowe/Nosid³a</option>
<option  value="333">Dla dzieci/Wózki i foteliki samochodowe/Wózki</option>
<option  value="335">Dla dzieci/Zabawki na dwór/Domki i namioty</option>
<option  value="338">Dla dzieci/Zabawki na dwór/Pla¿owe</option>
<option  value="343">Dla dzieci/Zabawki na dwór/Ogrodowe</option>
<option  value="294">Dla dzieci/Gra i nauka/Karty</option>
<option  value="296">Dla dzieci/Gra i nauka/Tablice do pisania</option>
<option  value="297">Dla dzieci/Gra i nauka/Zabawki kreatywne</option>
<option  value="348">Dla dzieci/Gra i nauka/Gry</option>
<option  value="402">Dla dzieci/Gra i nauka/Artyku³y szkolne</option>
<option  value="1876">Dla dzieci/Gra i nauka/Planszowe</option>
<option  value="1866">Dla dzieci/Pojazdy i gara¿e</option>
<option  value="1877">Dla dzieci/£ó¿eczka</option>
<option  value="3035">Dla dzieci/Samoloty</option>
<option  value="3036">Dla dzieci/Statki</option>
<option  value="404">AGD/Inne AGD</option>
<option  value="406">AGD/Kuchnia/Ch³odziarki (lodówki)</option>
<option  value="407">AGD/Kuchnia/Ch³odziarko-zamra¿arki</option>
<option  value="408">AGD/Kuchnia/Czajniki</option>
<option  value="410">AGD/Kuchnia/Ekspresy/Ci¶nieniowe</option>
<option  value="412">AGD/Kuchnia/Ekspresy/Zwyk³e</option>
<option  value="413">AGD/Kuchnia/Filtry do wody</option>
<option  value="414">AGD/Kuchnia/Frytkownice</option>
<option  value="415">AGD/Kuchnia/Gofrownice</option>
<option  value="416">AGD/Kuchnia/Grille</option>
<option  value="418">AGD/Kuchnia/Krajalnice</option>
<option  value="420">AGD/Kuchnia/Kuchnie/Do zabudowy</option>
<option  value="422">AGD/Kuchnia/Kuchnie/Kuchenki elektryczne</option>
<option  value="423">AGD/Kuchnia/Kuchnie/Kuchenki elektryczno-gazowe</option>
<option  value="424">AGD/Kuchnia/Kuchnie/Kuchenki gazowe</option>
<option  value="425">AGD/Kuchnia/Kuchnie/Kuchenki mikrofalowe</option>
<option  value="426">AGD/Kuchnia/Maszynki do mielenia</option>
<option  value="427">AGD/Kuchnia/Okapy</option>
<option  value="428">AGD/Kuchnia/Opiekacze</option>
<option  value="431">AGD/Kuchnia/Roboty kuchenne/Miksery</option>
<option  value="432">AGD/Kuchnia/Roboty kuchenne/Sokowirówki</option>
<option  value="433">AGD/Kuchnia/Tostery</option>
<option  value="434">AGD/Kuchnia/Zamra¿arki</option>
<option  value="435">AGD/Kuchnia/Zmywarki</option>
<option  value="454">AGD/Ró¿ne/Odkurzacze</option>
<option  value="455">AGD/Ró¿ne/Solaria</option>
<option  value="456">AGD/Ró¿ne/Termometry</option>
<option  value="457">AGD/Ró¿ne/Wagi</option>
<option  value="458">AGD/Ró¿ne/¯elazka</option>
<option  value="1883">AGD/Ró¿ne/Urz±dzenia czyszcz±ce/Profesjonalne</option>
<option  value="1884">AGD/Ró¿ne/Urz±dzenia czyszcz±ce/Domowe</option>
<option  value="1886">AGD/Ró¿ne/¦rodki chemiczne/Do mycia rêcznego</option>
<option  value="1887">AGD/Ró¿ne/¦rodki chemiczne/Do mycia maszynowego</option>
<option  value="459">Antyki i Sztuka/Antyki</option>
<option  value="463">Antyki i Sztuka/Sztuka/Malarstwo</option>
<option  value="464">Antyki i Sztuka/Sztuka/Rze¼ba</option>
<option  value="1890">Antyki i Sztuka/Figurki i Rze¼by/Ludzie</option>
<option  value="1891">Antyki i Sztuka/Figurki i Rze¼by/Zwierzêta</option>
<option  value="1892">Antyki i Sztuka/Figurki i Rze¼by/Z lampami</option>
<option  value="1893">Antyki i Sztuka/Figurki i Rze¼by/Z zegarami</option>
<option  value="474">Biuro/Artyku³y i sprzêt do prezentacji/Akcesoria do prezentacji</option>
<option  value="475">Biuro/Artyku³y i sprzêt do prezentacji/Akcesoria do tablic</option>
<option  value="476">Biuro/Artyku³y i sprzêt do prezentacji/Ekrany projekcyjne</option>
<option  value="477">Biuro/Artyku³y i sprzêt do prezentacji/Flipcharty</option>
<option  value="478">Biuro/Artyku³y i sprzêt do prezentacji/Folie prezentacyjne</option>
<option  value="480">Biuro/Artyku³y i sprzêt do prezentacji/Litery, tabliczki, piktogramy</option>
<option  value="481">Biuro/Artyku³y i sprzêt do prezentacji/Projektory multimedialne. Rzutniki</option>
<option  value="482">Biuro/Artyku³y i sprzêt do prezentacji/Rzutniki obrazu z folii</option>
<option  value="483">Biuro/Artyku³y i sprzêt do prezentacji/Rzutniki obrazu ze slajdów</option>
<option  value="484">Biuro/Artyku³y i sprzêt do prezentacji/Systemy planowania</option>
<option  value="488">Biuro/Artyku³y i sprzêt do prezentacji/Wska¼niki laserowe</option>
<option  value="3166">Biuro/Artyku³y i sprzêt do prezentacji/Identyfikatory</option>
<option  value="3167">Biuro/Artyku³y i sprzêt do prezentacji/Tablice</option>
<option  value="490">Biuro/Artyku³y pi¶mienne i akcesoria/Artyku³y kre¶larskie</option>
<option  value="491">Biuro/Artyku³y pi¶mienne i akcesoria/Cienkopisy</option>
<option  value="492">Biuro/Artyku³y pi¶mienne i akcesoria/D³ugopisy</option>
<option  value="493">Biuro/Artyku³y pi¶mienne i akcesoria/Ekskluzywne artyku³y do pisania</option>
<option  value="494">Biuro/Artyku³y pi¶mienne i akcesoria/Gumki, korektory</option>
<option  value="497">Biuro/Artyku³y pi¶mienne i akcesoria/Markery, zakre¶lacze</option>
<option  value="498">Biuro/Artyku³y pi¶mienne i akcesoria/Naboje z atramentem i wk³ady do d³ugopisów</option>
<option  value="499">Biuro/Artyku³y pi¶mienne i akcesoria/O³ówki</option>
<option  value="501">Biuro/Artyku³y pi¶mienne i akcesoria/Pióra kulkowe</option>
<option  value="502">Biuro/Artyku³y pi¶mienne i akcesoria/Temperówki</option>
<option  value="503">Biuro/Artyku³y pi¶mienne i akcesoria/Wk³ady do o³ówków mechanicznych</option>
<option  value="1895">Biuro/Artyku³y pi¶mienne i akcesoria/Pióra wieczne</option>
<option  value="506">Biuro/Galanteria biurowa/Akcesoria opakowaniowe</option>
<option  value="507">Biuro/Galanteria biurowa/Drobna galanteria biurowa</option>
<option  value="508">Biuro/Galanteria biurowa/Drobne akcesoria na biurko</option>
<option  value="509">Biuro/Galanteria biurowa/Dziurkacze do papieru</option>
<option  value="511">Biuro/Galanteria biurowa/Kleje</option>
<option  value="512">Biuro/Galanteria biurowa/No¿yczki i no¿yki biurowe</option>
<option  value="514">Biuro/Galanteria biurowa/Podk³adki i maty na biurko</option>
<option  value="515">Biuro/Galanteria biurowa/Przyborniki na biurko</option>
<option  value="516">Biuro/Galanteria biurowa/Ramki do informacji i zdjêæ</option>
<option  value="517">Biuro/Galanteria biurowa/Stemple</option>
<option  value="518">Biuro/Galanteria biurowa/Ta¶my klej±ce i biurowe</option>
<option  value="519">Biuro/Galanteria biurowa/Ta¶my pakowe</option>
<option  value="522">Biuro/Galanteria biurowa/Zszywacze</option>
<option  value="523">Biuro/Galanteria biurowa/Zszywki i spinacze</option>
<option  value="1896">Biuro/Galanteria biurowa/Obrazy</option>
<option  value="1897">Biuro/Galanteria biurowa/Ikony</option>
<option  value="1898">Biuro/Galanteria biurowa/Lustra</option>
<option  value="1899">Biuro/Galanteria biurowa/Papirusy</option>
<option  value="3168">Biuro/Galanteria biurowa/Podajniki do ta¶m</option>
<option  value="3169">Biuro/Galanteria biurowa/Opakowania</option>
<option  value="525">Biuro/Galanteria papiernicza/Bloczki do notatek</option>
<option  value="526">Biuro/Galanteria papiernicza/Bloki biurowe</option>
<option  value="527">Biuro/Galanteria papiernicza/Druki biurowe</option>
<option  value="528">Biuro/Galanteria papiernicza/Etykiety, kartki samoprzylepne</option>
<option  value="530">Biuro/Galanteria papiernicza/Kalka</option>
<option  value="532">Biuro/Galanteria papiernicza/Koperty</option>
<option  value="533">Biuro/Galanteria papiernicza/Notatniki, notesy, skorowidze</option>
<option  value="535">Biuro/Galanteria papiernicza/Papier/Papier faksowy</option>
<option  value="536">Biuro/Galanteria papiernicza/Papier/Papier kancelaryjny</option>
<option  value="537">Biuro/Galanteria papiernicza/Papier/Papier komputerowy</option>
<option  value="538">Biuro/Galanteria papiernicza/Papier/Papier ksero</option>
<option  value="539">Biuro/Galanteria papiernicza/Papier/Papier milimetrowy</option>
<option  value="540">Biuro/Galanteria papiernicza/Papier/Papiery specjalistyczn</option>
<option  value="541">Biuro/Galanteria papiernicza/Papier/Rolki do kas</option>
<option  value="542">Biuro/Galanteria papiernicza/Papier/Wk³ady do segregatorów</option>
<option  value="543">Biuro/Galanteria papiernicza/Papier/Zeszyty</option>
<option  value="546">Biuro/Materia³y eksploatacyjne/Do bindownic</option>
<option  value="547">Biuro/Materia³y eksploatacyjne/Do drukarek atramentowych</option>
<option  value="548">Biuro/Materia³y eksploatacyjne/Do drukarek etykiet</option>
<option  value="549">Biuro/Materia³y eksploatacyjne/Do drukarek ig³owych</option>
<option  value="550">Biuro/Materia³y eksploatacyjne/Do drukarek laserowych</option>
<option  value="551">Biuro/Materia³y eksploatacyjne/Do kalkulatorów</option>
<option  value="552">Biuro/Materia³y eksploatacyjne/Do kopiarek</option>
<option  value="553">Biuro/Materia³y eksploatacyjne/Do laminatorów</option>
<option  value="554">Biuro/Materia³y eksploatacyjne/Do maszyn do pisania</option>
<option  value="555">Biuro/Materia³y eksploatacyjne/Do prezentacji</option>
<option  value="556">Biuro/Materia³y eksploatacyjne/Do telefaksów</option>
<option  value="1900">Biuro/Materia³y eksploatacyjne/Do drukarek termosublimacyjnych</option>
<option  value="559">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Akcesoria do oprawy dokumentów</option>
<option  value="560">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Albumy ofertowe</option>
<option  value="561">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Deski z klipem</option>
<option  value="564">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Ofertówki</option>
<option  value="565">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Ok³adki na dokumenty</option>
<option  value="566">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Organizery</option>
<option  value="567">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Pojemniki na dokumenty</option>
<option  value="568">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Pó³ki i kasety na dokumenty</option>
<option  value="569">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Przek³adki do segregatorów</option>
<option  value="570">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Segregatory</option>
<option  value="571">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Skoroszyty</option>
<option  value="572">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Systemy archiwizacyjne</option>
<option  value="573">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Koszulki, teczki, tuby</option>
<option  value="575">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Wizytowniki</option>
<option  value="576">Biuro/Organizacja przechowywanie i archiwizacja dokumentów/Zak³adki indeksuj±ce</option>
<option  value="465">Biuro/Urz±dzenia biurowe/Akcesoria do urz±dzeñ biurowych</option>
<option  value="579">Biuro/Urz±dzenia biurowe/Bindownice</option>
<option  value="580">Biuro/Urz±dzenia biurowe/Drukarki etykiet</option>
<option  value="581">Biuro/Urz±dzenia biurowe/Gilotyny</option>
<option  value="583">Biuro/Urz±dzenia biurowe/Kalkulatory</option>
<option  value="584">Biuro/Urz±dzenia biurowe/Kopiarki</option>
<option  value="585">Biuro/Urz±dzenia biurowe/Laminatory</option>
<option  value="586">Biuro/Urz±dzenia biurowe/Liczarki banknotów</option>
<option  value="587">Biuro/Urz±dzenia biurowe/Maszyny do pisania</option>
<option  value="588">Biuro/Urz±dzenia biurowe/Niszczarki dokumentów</option>
<option  value="589">Biuro/Urz±dzenia biurowe/Organizery elektroniczne</option>
<option  value="590">Biuro/Urz±dzenia biurowe/Testery banknotów</option>
<option  value="591">Biuro/Urz±dzenia biurowe/T³umacze elektroniczne</option>
<option  value="592">Biuro/Urz±dzenia biurowe/Urz±dzenia wielofunkcyjne</option>
<option  value="593">Biuro/Urz±dzenia biurowe/Wagi do listów</option>
<option  value="3171">Biuro/Higiena w biurze/Artyku³y jednorazowe</option>
<option  value="3173">Biuro/Higiena w biurze/Kasetki na pieni±dze</option>
<option  value="3174">Biuro/Higiena w biurze/Worki na ¶mieci</option>
<option  value="3175">Biuro/Higiena w biurze/Kosze na ¶mieci</option>
<option  value="3176">Biuro/Higiena w biurze/Wycieraczki</option>
<option  value="3177">Biuro/Higiena w biurze/Papier toaletowy, rêczniki</option>
<option  value="3184">Biuro/Galanteria skórzana/Etui na klucze</option>
<option  value="3185">Biuro/Galanteria skórzana/Nesesery</option>
<option  value="3186">Biuro/Galanteria skórzana/Etui na okulary, pióra</option>
<option  value="3188">Biuro/Galanteria skórzana/Etui na wizytówki</option>
<option  value="3191">Biuro/Artyku³y spo¿ywcze/Herbata</option>
<option  value="3192">Biuro/Artyku³y spo¿ywcze/¦mietanka i mleko do kawy</option>
<option  value="3193">Biuro/Artyku³y spo¿ywcze/Kawa</option>
<option  value="3194">Biuro/Artyku³y spo¿ywcze/Przek±ski s³one</option>
<option  value="3196">Biuro/Galanteria szkolna/Bibu³a, krepina</option>
<option  value="3198">Biuro/Galanteria szkolna/Ok³adki na zeszyty</option>
<option  value="3199">Biuro/Galanteria szkolna/Pêdzelki</option>
<option  value="3200">Biuro/Galanteria szkolna/Bloki szkolne</option>
<option  value="3201">Biuro/Galanteria szkolna/Flamastry</option>
<option  value="3202">Biuro/Galanteria szkolna/Piórniki</option>
<option  value="3203">Biuro/Galanteria szkolna/Tablice szkolne</option>
<option  value="3204">Biuro/Galanteria szkolna/Cyrkle</option>
<option  value="3205">Biuro/Galanteria szkolna/Kredki</option>
<option  value="3206">Biuro/Galanteria szkolna/Plastelina, modelina</option>
<option  value="3208">Biuro/Galanteria szkolna/Dzienniczki ucznia</option>
<option  value="3209">Biuro/Galanteria szkolna/Linijki, ekierki, k±tomierze</option>
<option  value="3210">Biuro/Galanteria szkolna/Pomoce szkolne</option>
<option  value="3211">Biuro/Galanteria szkolna/Zeszyty papierów kolorowych</option>
<option  value="351">Bi¿uteria i Zegarki/Bi¿uteria inna</option>
<option  value="352">Bi¿uteria i Zegarki/Bi¿uteria srebrna</option>
<option  value="353">Bi¿uteria i Zegarki/Bi¿uteria z³ota</option>
<option  value="375">Bi¿uteria i Zegarki/Zegarki/Damskie</option>
<option  value="376">Bi¿uteria i Zegarki/Zegarki/Dzieciêce</option>
<option  value="377">Bi¿uteria i Zegarki/Zegarki/Mêskie</option>
<option  value="378">Bi¿uteria i Zegarki/Zegarki/Unisex</option>
<option  value="642">Film/Akcja</option>
<option  value="643">Film/Animowane</option>
<option  value="644">Film/Dokumentalny</option>
<option  value="645">Film/Dramat</option>
<option  value="646">Film/Edukacyjny</option>
<option  value="648">Film/Familijny</option>
<option  value="649">Film/Fantasy</option>
<option  value="650">Film/Historyczny</option>
<option  value="651">Film/Horror</option>
<option  value="653">Film/Katastroficzny</option>
<option  value="654">Film/Komedia</option>
<option  value="655">Film/Melodramat</option>
<option  value="656">Film/Muzyka</option>
<option  value="657">Film/Obyczajowy</option>
<option  value="658">Film/Przyrodniczy</option>
<option  value="659">Film/Romans</option>
<option  value="660">Film/Science Fiction</option>
<option  value="661">Film/Serial</option>
<option  value="662">Film/Thriller</option>
<option  value="663">Film/Western</option>
<option  value="664">Film/Wojenny</option>
<option  value="1905">Film/Sensacja</option>
<option  value="1907">Film/Specjalne</option>
<option  value="3114">Film/Bajki</option>
<option  value="3115">Film/Film polski</option>
<option  value="3116">Film/Kino ambitne</option>
<option  value="3117">Film/Kostiumowe</option>
<option  value="3119">Film/Religijne</option>
<option  value="706">Galanteria/Teczki/Aktówki</option>
<option  value="707">Galanteria/Teczki/Do bloku</option>
<option  value="710">Galanteria/Torby, walizki/Do paska</option>
<option  value="712">Galanteria/Torby, walizki/Na ubrania</option>
<option  value="713">Galanteria/Torby, walizki/Podró¿ne</option>
<option  value="1933">Galanteria/Torby, walizki/Podrêczne</option>
<option  value="1934">Galanteria/Torby, walizki/Na laptopa</option>
<option  value="714">Galanteria/Torebki</option>
<option  value="1935">Galanteria/My¶liwska</option>
<option  value="747">Komputery/Drukarki</option>
<option  value="751">Komputery/Kable, ta¶my, akcesoria</option>
<option  value="3124">Komputery/Monitory/Poni¿ej 14"</option>
<option  value="3125">Komputery/Monitory/14"-16"</option>
<option  value="3127">Komputery/Monitory/17"-19"</option>
<option  value="3129">Komputery/Monitory/21" i wiêksze</option>
<option  value="3131">Komputery/Monitory/LCD</option>
<option  value="3132">Komputery/Monitory/Wszystkie</option>
<option  value="753">Komputery/No¶niki danych</option>
<option  value="755">Komputery/Oprogramowanie/Administracyjne</option>
<option  value="756">Komputery/Oprogramowanie/Antywirusowe</option>
<option  value="757">Komputery/Oprogramowanie/Archiwizacyjne</option>
<option  value="758">Komputery/Oprogramowanie/Bazy danych</option>
<option  value="759">Komputery/Oprogramowanie/Biurowe</option>
<option  value="760">Komputery/Oprogramowanie/Graficzne</option>
<option  value="762">Komputery/Oprogramowanie/Internetowe i komunikacyjne</option>
<option  value="763">Komputery/Oprogramowanie/Kompilatory</option>
<option  value="764">Komputery/Oprogramowanie/Muzyczne</option>
<option  value="765">Komputery/Oprogramowanie/Narzêdziowe</option>
<option  value="766">Komputery/Oprogramowanie/Systemysieciowe</option>
<option  value="767">Komputery/Oprogramowanie/Systemy operacyjne</option>
<option  value="3138">Komputery/Oprogramowanie/Programy dla firm</option>
<option  value="3139">Komputery/Oprogramowanie/Programy edukacyjne</option>
<option  value="769">Komputery/Podzespo³y komputerowe/CD-ROM, DVD</option>
<option  value="770">Komputery/Podzespo³y komputerowe/Dyski twarde</option>
<option  value="771">Komputery/Podzespo³y komputerowe/G³o¶niki</option>
<option  value="773">Komputery/Podzespo³y komputerowe/Kable</option>
<option  value="774">Komputery/Podzespo³y komputerowe/Karty graficzne</option>
<option  value="775">Komputery/Podzespo³y komputerowe/Karty d¼wiekowe</option>
<option  value="776">Komputery/Podzespo³y komputerowe/Karty sieciowe</option>
<option  value="777">Komputery/Podzespo³y komputerowe/Klawiatury, myszy</option>
<option  value="778">Komputery/Podzespo³y komputerowe/Modemy</option>
<option  value="780">Komputery/Podzespo³y komputerowe/Nagrywarki</option>
<option  value="781">Komputery/Podzespo³y komputerowe/Obudowy</option>
<option  value="782">Komputery/Podzespo³y komputerowe/Pamiêci</option>
<option  value="783">Komputery/Podzespo³y komputerowe/Plotery</option>
<option  value="784">Komputery/Podzespo³y komputerowe/P³yty g³ówne</option>
<option  value="785">Komputery/Podzespo³y komputerowe/Procesory</option>
<option  value="786">Komputery/Podzespo³y komputerowe/Skanery</option>
<option  value="2016">Komputery/Podzespo³y komputerowe/Tunery TV</option>
<option  value="2017">Komputery/Podzespo³y komputerowe/Akcesoria USB</option>
<option  value="2018">Komputery/Podzespo³y komputerowe/Akcesoria FireWire</option>
<option  value="2019">Komputery/Podzespo³y komputerowe/Osprzêt sieciowy</option>
<option  value="2021">Komputery/Podzespo³y komputerowe/Combo</option>
<option  value="793">Komputery/Przeno¶ne/Notebooki</option>
<option  value="794">Komputery/Przeno¶ne/Palmtopy</option>
<option  value="795">Komputery/Zasilacze awaryjne</option>
<option  value="796">Komputery/Zestawy komputerowe</option>
<option  value="2022">Komputery/Serwery</option>
<option  value="3436">Komputery/Internet/Narzêdzia internetowe</option>
<option  value="3437">Komputery/Internet/Produkcja WWW</option>
<option  value="3438">Komputery/Internet/Rejestracja domen</option>
<option  value="3440">Komputery/Konsole do gier/Game Boy Advance</option>
<option  value="3441">Komputery/Konsole do gier/Nintendo GameCube</option>
<option  value="3442">Komputery/Konsole do gier/Sony PlayStation - PSX</option>
<option  value="3443">Komputery/Konsole do gier/Sony PlayStation2 - PS2</option>
<option  value="3444">Komputery/Konsole do gier/Automaty do gier</option>
<option  value="3012">Komputery/Multimedia</option>
<option  value="3451">Komputery/Kontrolery/Kontrolery ATA</option>
<option  value="3452">Komputery/Kontrolery/Kontrolery SCSI</option>
<option  value="3453">Komputery/Kontrolery/Kontrolery USB</option>
<option  value="3454">Komputery/Kontrolery/Kontrolery gier</option>
<option  value="3014">Komputery/Torby komputerowe</option>
<option  value="3445">Komputery/Napêdy no¶ników</option>
<option  value="3446">Komputery/Zabezpieczenia</option>
<option  value="3450">Komputery/UPS</option>
<option  value="3455">Komputery/Tusze, tonery</option>
<option  value="3456">Komputery/GPS</option>
<option  value="798">Ksi±¿ki i Czasopisma/Czasopisma/Codzienne</option>
<option  value="799">Ksi±¿ki i Czasopisma/Czasopisma/Dla dzieci</option>
<option  value="800">Ksi±¿ki i Czasopisma/Czasopisma/Dla kobiet</option>
<option  value="801">Ksi±¿ki i Czasopisma/Czasopisma/Dla mê¿czyzn</option>
<option  value="802">Ksi±¿ki i Czasopisma/Czasopisma/Dla m³odzie¿y</option>
<option  value="803">Ksi±¿ki i Czasopisma/Czasopisma/Dom Ogród Architektura</option>
<option  value="804">Ksi±¿ki i Czasopisma/Czasopisma/Ekonomia i biznes</option>
<option  value="805">Ksi±¿ki i Czasopisma/Czasopisma/Film</option>
<option  value="806">Ksi±¿ki i Czasopisma/Czasopisma/Informatyka</option>
<option  value="808">Ksi±¿ki i Czasopisma/Czasopisma/Literackie</option>
<option  value="809">Ksi±¿ki i Czasopisma/Czasopisma/Motoryzacyjne</option>
<option  value="811">Ksi±¿ki i Czasopisma/Czasopisma/Popularnonaukowe</option>
<option  value="812">Ksi±¿ki i Czasopisma/Czasopisma/Sport i rekreacja</option>
<option  value="813">Ksi±¿ki i Czasopisma/Czasopisma/W jêz. obcych</option>
<option  value="2045">Ksi±¿ki i Czasopisma/Nauka i edukacja/Lektury szkolne</option>
<option  value="848">Meble/Akcesoria meblowe i dodatki</option>
<option  value="852">Meble/Meble artystyczne antyki/Meble</option>
<option  value="2240">Meble/Meble artystyczne antyki/Lampy i aba¿ury</option>
<option  value="855">Meble/Meble biurowe/Biurka</option>
<option  value="856">Meble/Meble biurowe/Fotele</option>
<option  value="858">Meble/Meble biurowe/Krzes³a obrotowe</option>
<option  value="859">Meble/Meble biurowe/Krzes³a stacjonarne</option>
<option  value="860">Meble/Meble biurowe/Meble modu³owe</option>
<option  value="861">Meble/Meble biurowe/Metalowe szafy i rega³y</option>
<option  value="862">Meble/Meble biurowe/Podk³adki pod fotele</option>
<option  value="863">Meble/Meble biurowe/Stoliki komputerowe</option>
<option  value="864">Meble/Meble biurowe/Stoliki prezentacyjne</option>
<option  value="865">Meble/Meble biurowe/Szafy kartotekowe</option>
<option  value="866">Meble/Meble biurowe/Wieszaki</option>
<option  value="871">Meble/Meble dla dzieci/Komplety wypoczynkowe</option>
<option  value="872">Meble/Meble dla dzieci/Krzes³a</option>
<option  value="873">Meble/Meble dla dzieci/£ó¿ka</option>
<option  value="875">Meble/Meble dla dzieci/Pó³ki</option>
<option  value="876">Meble/Meble dla dzieci/Sofy</option>
<option  value="877">Meble/Meble dla dzieci/Stoliki</option>
<option  value="878">Meble/Meble dla dzieci/Sto³y</option>
<option  value="879">Meble/Meble dla dzieci/Szafy i szafki</option>
<option  value="2241">Meble/Meble dla dzieci/Kufry</option>
<option  value="2242">Meble/Meble dla dzieci/Komody</option>
<option  value="883">Meble/Meble dla niemowl±t/Kojce niemowlêce</option>
<option  value="884">Meble/Meble dla niemowl±t/Komody z przewijakiem</option>
<option  value="885">Meble/Meble dla niemowl±t/Krzes³a do karmienia</option>
<option  value="886">Meble/Meble dla niemowl±t/Le¿aczki</option>
<option  value="887">Meble/Meble dla niemowl±t/£ó¿eczka niemowlêce</option>
<option  value="888">Meble/Meble dla niemowl±t/Materace do ³ó¿ek niemowlêcych</option>
<option  value="889">Meble/Meble dla niemowl±t/Materace do przewijania</option>
<option  value="2243">Meble/Meble dla niemowl±t/Szafy</option>
<option  value="890">Meble/Meble do pokoju dziennego</option>
<option  value="902">Meble/Meble do RTV</option>
<option  value="903">Meble/Meble do sypialni</option>
<option  value="911">Meble/Meble kuchenne</option>
<option  value="912">Meble/Meble ³azienkowe</option>
<option  value="919">Meble/Meble m³odzie¿owe</option>
<option  value="938">Meble/Meble na zamówienie/Kredensy</option>
<option  value="948">Meble/Meble ogrodowe</option>
<option  value="2244">Meble/Meble do przedpokoju</option>
<option  value="3413">Meble/Meble do jadalni</option>
<option  value="976">Motoryzacja/Samochody</option>
<option  value="979">Motoryzacja/Czê¶ci samochodowe/Akumulatory</option>
<option  value="980">Motoryzacja/Czê¶ci samochodowe/Amortyzatory</option>
<option  value="981">Motoryzacja/Czê¶ci samochodowe/Ch³odzenie silnika</option>
<option  value="982">Motoryzacja/Czê¶ci samochodowe/Czê¶ci blacharskie</option>
<option  value="983">Motoryzacja/Czê¶ci samochodowe/Czê¶ci silnika</option>
<option  value="984">Motoryzacja/Czê¶ci samochodowe/Elementy wnêtrza</option>
<option  value="987">Motoryzacja/Czê¶ci samochodowe/Instalacja elektryczna</option>
<option  value="988">Motoryzacja/Czê¶ci samochodowe/Lampy, reflektory</option>
<option  value="989">Motoryzacja/Czê¶ci samochodowe/£o¿yska</option>
<option  value="990">Motoryzacja/Czê¶ci samochodowe/Napinacze, paski</option>
<option  value="991">Motoryzacja/Czê¶ci samochodowe/Poduszki silnika</option>
<option  value="992">Motoryzacja/Czê¶ci samochodowe/Przeguby, os³ony, uszczelniacze pó³osi</option>
<option  value="994">Motoryzacja/Czê¶ci samochodowe/Skrzynie biegów</option>
<option  value="995">Motoryzacja/Czê¶ci samochodowe/Sprzêg³a</option>
<option  value="996">Motoryzacja/Czê¶ci samochodowe/Szyby</option>
<option  value="998">Motoryzacja/Czê¶ci samochodowe/T³umiki, uk³ady wydechowe</option>
<option  value="999">Motoryzacja/Czê¶ci samochodowe/Uk³ad hamulcowy</option>
<option  value="1000">Motoryzacja/Czê¶ci samochodowe/Uk³ad kierowniczy</option>
<option  value="1001">Motoryzacja/Czê¶ci samochodowe/Uk³ad zawieszenia</option>
<option  value="1002">Motoryzacja/Czê¶ci samochodowe/Uszczelki</option>
<option  value="1003">Motoryzacja/Czê¶ci samochodowe/Zderzaki</option>
<option  value="1004">Motoryzacja/Dostawcze</option>
<option  value="1005">Motoryzacja/Felgi</option>
<option  value="1007">Motoryzacja/Inne produkty/Dodatki do paliwa i oleju</option>
<option  value="1009">Motoryzacja/Inne produkty/Oleje</option>
<option  value="1010">Motoryzacja/Inne produkty/Smary</option>
<option  value="1013">Motoryzacja/Jedno¶lady/Czê¶ci</option>
<option  value="1015">Motoryzacja/Jedno¶lady/Kaski</option>
<option  value="1016">Motoryzacja/Jedno¶lady/Motocykle</option>
<option  value="1017">Motoryzacja/Jedno¶lady/Motorowery i skutery</option>
<option  value="1018">Motoryzacja/Jedno¶lady/Ubrania</option>
<option  value="1020">Motoryzacja/Kosmetyki/Felgi i opony</option>
<option  value="1022">Motoryzacja/Kosmetyki/Karoseria</option>
<option  value="1024">Motoryzacja/Kosmetyki/¦rodki zimowe</option>
<option  value="1025">Motoryzacja/Opony</option>
<option  value="1029">Motoryzacja/Produkty zimowe/Odmra¿acze</option>
<option  value="1030">Motoryzacja/Produkty zimowe/P³yny do ch³odnic</option>
<option  value="1031">Motoryzacja/Produkty zimowe/P³yny do spryskiwaczy</option>
<option  value="2247">Motoryzacja/Przyczepy/Przyczepy nowe/Baga¿owe</option>
<option  value="2248">Motoryzacja/Przyczepy/Przyczepy nowe/Ciê¿arowe</option>
<option  value="2249">Motoryzacja/Przyczepy/Przyczepy nowe/Furgony</option>
<option  value="2250">Motoryzacja/Przyczepy/Przyczepy nowe/Handlowe</option>
<option  value="2251">Motoryzacja/Przyczepy/Przyczepy nowe/Izotermy</option>
<option  value="2252">Motoryzacja/Przyczepy/Przyczepy nowe/Kempingowe</option>
<option  value="2253">Motoryzacja/Przyczepy/Przyczepy nowe/Koñskie</option>
<option  value="2254">Motoryzacja/Przyczepy/Przyczepy nowe/Lawety</option>
<option  value="2255">Motoryzacja/Przyczepy/Przyczepy nowe/Motocyklowe</option>
<option  value="2256">Motoryzacja/Przyczepy/Przyczepy nowe/Pod mini koparki</option>
<option  value="2257">Motoryzacja/Przyczepy/Przyczepy nowe/Pod skutery</option>
<option  value="2258">Motoryzacja/Przyczepy/Przyczepy nowe/Pod³odziowe</option>
<option  value="2259">Motoryzacja/Przyczepy/Przyczepy nowe/Samochody kempingowe</option>
<option  value="2261">Motoryzacja/Tuning/Alufelgi</option>
<option  value="2262">Motoryzacja/Tuning/Ga³ki</option>
<option  value="2264">Motoryzacja/Tuning/Hamulce</option>
<option  value="2265">Motoryzacja/Tuning/Kierownice</option>
<option  value="2267">Motoryzacja/Tuning/Spoilery</option>
<option  value="2268">Motoryzacja/Tuning/Uk³ady wydechowe</option>
<option  value="2269">Motoryzacja/Tuning/Filtry powietrza</option>
<option  value="2272">Motoryzacja/Tuning/Magnetyzery paliwa</option>
<option  value="2275">Motoryzacja/Tuning/Wa³ki</option>
<option  value="2276">Motoryzacja/Tuning/Przewody zap³onowe</option>
<option  value="1036">Multimedia i Gry/Edukacyjne</option>
<option  value="1037">Multimedia i Gry/Fabularne</option>
<option  value="1038">Multimedia i Gry/Familijne</option>
<option  value="1039">Multimedia i Gry/Logiczne</option>
<option  value="1040">Multimedia i Gry/Przygodowe</option>
<option  value="1041">Multimedia i Gry/Zrêczno¶ciowe</option>
<option  value="1043">Multimedia i Gry/Kompilacje</option>
<option  value="1045">Multimedia i Gry/Strategiczne</option>
<option  value="1048">Multimedia i Gry/Symulacje</option>
<option  value="1050">Multimedia i Gry/Wy¶cigi</option>
<option  value="1058">Multimedia i Gry/Sportowe</option>
<option  value="2277">Multimedia i Gry/Gry akcji</option>
<option  value="2286">Multimedia i Gry/Sprzêt i akcesoria</option>
<option  value="1098">Muzyka/Instrumenty/Dête</option>
<option  value="1099">Muzyka/Instrumenty/Elektroniczne</option>
<option  value="1102">Muzyka/Instrumenty/Klawiszowe</option>
<option  value="1103">Muzyka/Instrumenty/Perkusyjne</option>
<option  value="1104">Muzyka/Instrumenty/Smyczkowe</option>
<option  value="1105">Muzyka/Instrumenty/Strunowe</option>
<option  value="1107">Muzyka/Nagrania/AcidJazz</option>
<option  value="1108">Muzyka/Nagrania/Alternatywna</option>
<option  value="1109">Muzyka/Nagrania/Ambient</option>
<option  value="1110">Muzyka/Nagrania/Blues</option>
<option  value="1111">Muzyka/Nagrania/Country</option>
<option  value="1112">Muzyka/Nagrania/Dawna</option>
<option  value="1113">Muzyka/Nagrania/Dzieciêca</option>
<option  value="1114">Muzyka/Nagrania/Filmowa</option>
<option  value="1115">Muzyka/Nagrania/Folk</option>
<option  value="1116">Muzyka/Nagrania/Funk</option>
<option  value="1117">Muzyka/Nagrania/Gospel</option>
<option  value="1118">Muzyka/Nagrania/Hip-Hop</option>
<option  value="1119">Muzyka/Nagrania/House</option>
<option  value="1120">Muzyka/Nagrania/Industrial</option>
<option  value="1121">Muzyka/Nagrania/Jazz</option>
<option  value="1122">Muzyka/Nagrania/Jungle</option>
<option  value="1123">Muzyka/Nagrania/Kabaretowa</option>
<option  value="1124">Muzyka/Nagrania/Klasyczna</option>
<option  value="1125">Muzyka/Nagrania/Minimal</option>
<option  value="1126">Muzyka/Nagrania/New Age</option>
<option  value="1127">Muzyka/Nagrania/Opera</option>
<option  value="1128">Muzyka/Nagrania/Piosenka Aktorska i Poezja ¶piewana</option>
<option  value="1129">Muzyka/Nagrania/Pop</option>
<option  value="1130">Muzyka/Nagrania/Reggae</option>
<option  value="1131">Muzyka/Nagrania/Religijna</option>
<option  value="1132">Muzyka/Nagrania/Rhythm</option>
<option  value="1133">Muzyka/Nagrania/Rock</option>
<option  value="1134">Muzyka/Nagrania/Sk³adanka</option>
<option  value="1135">Muzyka/Nagrania/Szanty</option>
<option  value="1136">Muzyka/Nagrania/¦wi±teczna</option>
<option  value="1140">Muzyka/Nagrania/Trip-Hop</option>
<option  value="1141">Muzyka/Nagrania/Teatralna i filmowa</option>
<option  value="1142">Muzyka/Nagrania/Techno</option>
<option  value="1143">Muzyka/Nagrania/Trance</option>
<option  value="1145">Muzyka/Nagrania/Wokalistyka</option>
<option  value="2366">Muzyka/Nagrania/Elektroniczna</option>
<option  value="2367">Muzyka/Nagrania/Rap</option>
<option  value="3226">Muzyka/Nagrania/R &amp; B</option>
<option  value="1148">Odzie¿/Damska/Bielizna/Biustonosze</option>
<option  value="1149">Odzie¿/Damska/Bielizna/Body</option>
<option  value="1150">Odzie¿/Damska/Bielizna/Halki</option>
<option  value="1152">Odzie¿/Damska/Bielizna/Bielizna nocna</option>
<option  value="1154">Odzie¿/Damska/Bielizna/Majtki</option>
<option  value="1155">Odzie¿/Damska/Bielizna/Koszulki, podkoszulki</option>
<option  value="2370">Odzie¿/Damska/Bielizna/Gorsety</option>
<option  value="1156">Odzie¿/Damska/Bluzki</option>
<option  value="1157">Odzie¿/Damska/Bluzy</option>
<option  value="1159">Odzie¿/Damska/Komplety damskie</option>
<option  value="1160">Odzie¿/Damska/Koszulki</option>
<option  value="1161">Odzie¿/Damska/Nakrycia g³owy</option>
<option  value="1162">Odzie¿/Damska/Odzie¿ ci±¿owa</option>
<option  value="1163">Odzie¿/Damska/P³aszcze i kurtki</option>
<option  value="1164">Odzie¿/Damska/Rajstopy, skarpetki</option>
<option  value="1165">Odzie¿/Damska/Rêkawiczki</option>
<option  value="1167">Odzie¿/Damska/Spodnie</option>
<option  value="1168">Odzie¿/Damska/Spódniczki</option>
<option  value="1169">Odzie¿/Damska/Stroje k±pielowe</option>
<option  value="1170">Odzie¿/Damska/Sukienki</option>
<option  value="1171">Odzie¿/Damska/Swetry</option>
<option  value="1172">Odzie¿/Damska/Szaliki</option>
<option  value="1173">Odzie¿/Damska/Topiki</option>
<option  value="1174">Odzie¿/Damska/Tuniki</option>
<option  value="1175">Odzie¿/Damska/¯akiety</option>
<option  value="2371">Odzie¿/Damska/Chusty</option>
<option  value="2372">Odzie¿/Damska/Apaszki</option>
<option  value="2373">Odzie¿/Damska/Szale</option>
<option  value="1179">Odzie¿/Dla niemowl±t/Czapeczki</option>
<option  value="1181">Odzie¿/Dla niemowl±t/Komplety</option>
<option  value="1182">Odzie¿/Dla niemowl±t/Kurtki</option>
<option  value="1183">Odzie¿/Dla niemowl±t/Pajace</option>
<option  value="1184">Odzie¿/Dla niemowl±t/Rajstopki</option>
<option  value="1185">Odzie¿/Dla niemowl±t/Rampersy</option>
<option  value="1188">Odzie¿/Dla niemowl±t/¦pioszki</option>
<option  value="1189">Odzie¿/Dla niemowl±t/¦piwory i ro¿ki</option>
<option  value="1192">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Swetry, bluzy</option>
<option  value="1193">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Czapki szaliki rêkawiczki</option>
<option  value="1195">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/K±pielowe</option>
<option  value="1196">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Koszule</option>
<option  value="1199">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Pi¿amy</option>
<option  value="1200">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Skarpetki i rajstopy</option>
<option  value="1202">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Spódnice</option>
<option  value="3019">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/0 - 1 lat</option>
<option  value="3020">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/1 - 3 lat</option>
<option  value="3021">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/3 - 7 lat</option>
<option  value="3022">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/7 - 12 lat</option>
<option  value="3249">Odzie¿/Odzie¿ dzieciêca i m³odzie¿owa/Codzienna</option>
<option  value="1207">Odzie¿/Mêska/Blielizna</option>
<option  value="1211">Odzie¿/Mêska/Wizytowa</option>
<option  value="1218">Odzie¿/Mêska/Skarpetki</option>
<option  value="2375">Odzie¿/Mêska/Du¿e rozmiary</option>
<option  value="1220">Odzie¿/Obuwie</option>
<option  value="1226">Odzie¿/Odzie¿ ochronna i robocza/Inna</option>
<option  value="1227">Odzie¿/Odzie¿ ochronna i robocza/Ogrodowa</option>
<option  value="666">RTV i Foto/Akcesoria foto/Albumy</option>
<option  value="667">RTV i Foto/Akcesoria foto/Baterie</option>
<option  value="669">RTV i Foto/Akcesoria foto/Filmy</option>
<option  value="672">RTV i Foto/Akcesoria foto/Lupy</option>
<option  value="673">RTV i Foto/Akcesoria foto/¦wiat³omierze</option>
<option  value="674">RTV i Foto/Akcesoria foto/Torby statywy</option>
<option  value="1909">RTV i Foto/Akcesoria foto/Do aparatów cyfrowych/Stacje dokuj±ce</option>
<option  value="1911">RTV i Foto/Akcesoria foto/Do aparatów cyfrowych/Zasilacze</option>
<option  value="1912">RTV i Foto/Akcesoria foto/Do aparatów cyfrowych/Karty Pamiêci</option>
<option  value="1922">RTV i Foto/Akcesoria foto/Akumulatory i ³adowarki</option>
<option  value="675">RTV i Foto/Aparaty</option>
<option  value="676">RTV i Foto/APS</option>
<option  value="678">RTV i Foto/Aparaty ¶rednioformatowe</option>
<option  value="679">RTV i Foto/Aparaty kompaktowe</option>
<option  value="680">RTV i Foto/Aparaty lustrzankowe</option>
<option  value="682">RTV i Foto/Lampy</option>
<option  value="683">RTV i Foto/Lunety, lornetki, teleskopy</option>
<option  value="684">RTV i Foto/Obiektywy</option>
<option  value="685">RTV i Foto/Projektory do slajdów</option>
<option  value="686">RTV i Foto/Statywy</option>
<option  value="1231">RTV i Foto/Audio/G³o¶niki, mikrofony</option>
<option  value="1235">RTV i Foto/Audio/Komponenty Hi-Fi</option>
<option  value="1236">RTV i Foto/Audio/Anteny</option>
<option  value="1252">RTV i Foto/Audio/Spacerowe/Mp3</option>
<option  value="1253">RTV i Foto/Audio/Spacerowe/Odtwarzacze CD</option>
<option  value="1258">RTV i Foto/Audio/Zestawy i wie¿e</option>
<option  value="2475">RTV i Foto/Audio/Zestawy DJ/Gramofony dla DJ</option>
<option  value="2476">RTV i Foto/Audio/Zestawy DJ/Odtwarzacze CD dla DJ</option>
<option  value="2472">RTV i Foto/Audio/Sprzêt Studyjny</option>
<option  value="1260">RTV i Foto/Elektronika/Aparatura pomiarowa</option>
<option  value="1261">RTV i Foto/Elektronika/Baterie i akumulatory</option>
<option  value="1262">RTV i Foto/Elektronika/Elementy elektroniczne</option>
<option  value="1264">RTV i Foto/Elektronika/Kable i przewody</option>
<option  value="1265">RTV i Foto/Elektronika/Karty chipowe</option>
<option  value="1266">RTV i Foto/Elektronika/Narzêdzia elektroniczne</option>
<option  value="1267">RTV i Foto/Elektronika/Programatory</option>
<option  value="1268">RTV i Foto/Elektronika/Sprzêt krótkofalowy i CB-Radio</option>
<option  value="2376">RTV i Foto/Elektronika/Odbiorniki GPS</option>
<option  value="1270">RTV i Foto/Samochodowe</option>
<option  value="1281">RTV i Foto/Telewizory/14" - 20"</option>
<option  value="1282">RTV i Foto/Telewizory/21" - 29"</option>
<option  value="1284">RTV i Foto/Telewizory/Powy¿ej 29"</option>
<option  value="1294">RTV i Foto/TV Sat/Dekodery</option>
<option  value="1295">RTV i Foto/TV Sat/Konwertery</option>
<option  value="1297">RTV i Foto/TV Sat/Tunery</option>
<option  value="1298">RTV i Foto/TV Sat/Zestawy</option>
<option  value="1300">RTV i Foto/Video i DVD/DVD</option>
<option  value="1304">RTV i Foto/Video i DVD/Kamery/Analogowe</option>
<option  value="1305">RTV i Foto/Video i DVD/Kamery/Cyfrowe</option>
<option  value="2377">RTV i Foto/Video i DVD/Kamery/Internetowe</option>
<option  value="1306">RTV i Foto/Video i DVD/Magnetowidy</option>
<option  value="1310">RTV i Foto/Video i DVD/No¶niki/Kasety</option>
<option  value="2379">RTV i Foto/Video i DVD/Edycja</option>
<option  value="1313">RTV i Foto/Kino domowe/Zestawy kina domowego</option>
<option  value="1314">RTV i Foto/Kino domowe/Plasma</option>
<option  value="4179">RTV i Foto/Kino domowe/Amplitunery</option>
<option  value="1925">RTV i Foto/Aparaty cyfrowe/Najtañsze aparaty dla amatorów fotografii!</option>
<option  value="1926">RTV i Foto/Aparaty cyfrowe/Aparaty cyfrowe pó³profesjonalne</option>
<option  value="1928">RTV i Foto/Aparaty cyfrowe/Aparaty cyfrowe profesjonalne</option>
<option  value="3258">RTV i Foto/Zasilanie/£adowarki</option>
<option  value="1413">Art. Spo¿ywcze/Alkohole/Alkohole gatunkowe</option>
<option  value="1414">Art. Spo¿ywcze/Alkohole/Piwo</option>
<option  value="2389">Art. Spo¿ywcze/Alkohole/Wina/Wina czerwone/Stylowe</option>
<option  value="2390">Art. Spo¿ywcze/Alkohole/Wina/Wina czerwone/Dla koneserów</option>
<option  value="2391">Art. Spo¿ywcze/Alkohole/Wina/Wina bia³e</option>
<option  value="2403">Art. Spo¿ywcze/Alkohole/Wina/Akcesoria winiarskie</option>
<option  value="1416">Art. Spo¿ywcze/Alkohole/Wódki</option>
<option  value="2397">Art. Spo¿ywcze/Alkohole/Szampany i wina musuj±ce</option>
<option  value="2399">Art. Spo¿ywcze/Alkohole/Koniaki</option>
<option  value="2400">Art. Spo¿ywcze/Alkohole/Whisky</option>
<option  value="2401">Art. Spo¿ywcze/Alkohole/Inne alkohole</option>
<option  value="2402">Art. Spo¿ywcze/Alkohole/Akcesoria, upominki alkoholowe</option>
<option  value="1418">Art. Spo¿ywcze/Art. sypkie/Cukier</option>
<option  value="1419">Art. Spo¿ywcze/Art. sypkie/Kasze</option>
<option  value="1420">Art. Spo¿ywcze/Art. sypkie/M±ka</option>
<option  value="1421">Art. Spo¿ywcze/Art. sypkie/Ry¿</option>
<option  value="3283">Art. Spo¿ywcze/Art. sypkie/Nasiona</option>
<option  value="1423">Art. Spo¿ywcze/Budynie, galaretki, kisiele/Budyñ</option>
<option  value="1424">Art. Spo¿ywcze/Budynie, galaretki, kisiele/Galaretki owocowe</option>
<option  value="1425">Art. Spo¿ywcze/Budynie, galaretki, kisiele/Kisiel</option>
<option  value="1427">Art. Spo¿ywcze/Herbaty</option>
<option  value="1433">Art. Spo¿ywcze/Kawy</option>
<option  value="1439">Art. Spo¿ywcze/Konserwy i dania gotowe/Dania gotowe</option>
<option  value="1441">Art. Spo¿ywcze/Konserwy i dania gotowe/Konserwy miêsne</option>
<option  value="1442">Art. Spo¿ywcze/Konserwy i dania gotowe/Konserwy rybne</option>
<option  value="1445">Art. Spo¿ywcze/Lody/Lodowe ciasta, rolady</option>
<option  value="1446">Art. Spo¿ywcze/Lody/Lody, mieszanki lodowe</option>
<option  value="1447">Art. Spo¿ywcze/Lody/Torty lodowe</option>
<option  value="1449">Art. Spo¿ywcze/Makarony/Inne (makarony)</option>
<option  value="1450">Art. Spo¿ywcze/Makarony/Makaron lasagne</option>
<option  value="1451">Art. Spo¿ywcze/Makarony/Makaron muszelki</option>
<option  value="1452">Art. Spo¿ywcze/Makarony/Makaron nitki</option>
<option  value="1453">Art. Spo¿ywcze/Makarony/Makaron rurki</option>
<option  value="1454">Art. Spo¿ywcze/Makarony/Makaron spaghetti</option>
<option  value="1455">Art. Spo¿ywcze/Makarony/Makaron ¶widerki</option>
<option  value="1456">Art. Spo¿ywcze/Makarony/Makaron wst±¿ki</option>
<option  value="1458">Art. Spo¿ywcze/Miêso/Drób</option>
<option  value="1459">Art. Spo¿ywcze/Miêso/Miêso wieprzowe</option>
<option  value="1460">Art. Spo¿ywcze/Miêso/Miêso wo³owe</option>
<option  value="1462">Art. Spo¿ywcze/Mro¿onki/Frytki</option>
<option  value="1463">Art. Spo¿ywcze/Mro¿onki/Mro¿one dania garma¿eryjne</option>
<option  value="1464">Art. Spo¿ywcze/Mro¿onki/Mro¿one dania warzywne</option>
<option  value="1465">Art. Spo¿ywcze/Mro¿onki/Mro¿onki rybne i owoce morza</option>
<option  value="1466">Art. Spo¿ywcze/Mro¿onki/Mro¿onki warzywne i owocowe</option>
<option  value="1467">Art. Spo¿ywcze/Mro¿onki/Pizza</option>
<option  value="1470">Art. Spo¿ywcze/Nabia³/Jajka</option>
<option  value="1471">Art. Spo¿ywcze/Nabia³/Jogurty</option>
<option  value="1472">Art. Spo¿ywcze/Nabia³/Napoje mleczne</option>
<option  value="1473">Art. Spo¿ywcze/Nabia³/Mas³a i margaryny</option>
<option  value="1475">Art. Spo¿ywcze/Nabia³/Mleko i ¶mietana</option>
<option  value="1476">Art. Spo¿ywcze/Nabia³/Serki homogenizowane</option>
<option  value="1477">Art. Spo¿ywcze/Nabia³/Sery bia³e, twarogi</option>
<option  value="1478">Art. Spo¿ywcze/Nabia³/Sery ple¶niowe</option>
<option  value="1479">Art. Spo¿ywcze/Nabia³/Sery ¿ó³te</option>
<option  value="3286">Art. Spo¿ywcze/Nabia³/Sery topione</option>
<option  value="1469">Art. Spo¿ywcze/Napoje, soki</option>
<option  value="1484">Art. Spo¿ywcze/Wody mineralne</option>
<option  value="1485">Art. Spo¿ywcze/Octy</option>
<option  value="1487">Art. Spo¿ywcze/Pieczywo/Inne (pieczywo)</option>
<option  value="1488">Art. Spo¿ywcze/Pieczywo/Pieczywo chrupkie i suchary</option>
<option  value="1489">Art. Spo¿ywcze/Pieczywo/Pieczywo razowe i pe³noziarn.</option>
<option  value="1490">Art. Spo¿ywcze/Pieczywo/Pieczywo ¶wie¿e</option>
<option  value="1491">Art. Spo¿ywcze/Pieczywo/Pieczywo tostowe</option>
<option  value="1492">Art. Spo¿ywcze/Pieczywo/Pieczywo ¿ytnie i pszenne</option>
<option  value="1493">Art. Spo¿ywcze/Pieczywo/Pumpernikiel</option>
<option  value="1499">Art. Spo¿ywcze/Po¿ywienie dla zwierz±t/Po¿ywienie dla kotów</option>
<option  value="1500">Art. Spo¿ywcze/Po¿ywienie dla zwierz±t/Po¿ywienie dla psów</option>
<option  value="1502">Art. Spo¿ywcze/Przek±ski/Chipsy</option>
<option  value="1503">Art. Spo¿ywcze/Przek±ski/Chrupki</option>
<option  value="1505">Art. Spo¿ywcze/Przek±ski/Orzeszki</option>
<option  value="1506">Art. Spo¿ywcze/Przek±ski/Paluszki</option>
<option  value="1508">Art. Spo¿ywcze/Przetwory owoc.-warzyw./D¿emy i konfitury</option>
<option  value="1510">Art. Spo¿ywcze/Przetwory owoc.-warzyw./Marynaty</option>
<option  value="1511">Art. Spo¿ywcze/Przetwory owoc.-warzyw./Owoce w puszkach</option>
<option  value="1512">Art. Spo¿ywcze/Przetwory owoc.-warzyw./Przetwory warzywne</option>
<option  value="1520">Art. Spo¿ywcze/Sosy, przyprawy/Przyprawy</option>
<option  value="1521">Art. Spo¿ywcze/Sosy, przyprawy/Sosy</option>
<option  value="1522">Art. Spo¿ywcze/Sosy, przyprawy/Sosy w proszku</option>
<option  value="1523">Art. Spo¿ywcze/Sosy, przyprawy/Sosy zimne, chrzany</option>
<option  value="1527">Art. Spo¿ywcze/Ryby i owoce morza/Anchovies</option>
<option  value="1529">Art. Spo¿ywcze/Ryby i owoce morza/Kawior</option>
<option  value="1530">Art. Spo¿ywcze/Ryby i owoce morza/£oso¶</option>
<option  value="1531">Art. Spo¿ywcze/Ryby i owoce morza/Owoce morza</option>
<option  value="1532">Art. Spo¿ywcze/Ryby i owoce morza/Ryby ¶wie¿e</option>
<option  value="1533">Art. Spo¿ywcze/Ryby i owoce morza/¦ledzie</option>
<option  value="1535">Art. Spo¿ywcze/S³odycze/Batony</option>
<option  value="1536">Art. Spo¿ywcze/S³odycze/Ciasta, ciastka, desery, herbatniki,biszkopty</option>
<option  value="1540">Art. Spo¿ywcze/S³odycze/Cukierki, karmelki</option>
<option  value="1541">Art. Spo¿ywcze/S³odycze/Czekoladki, bombonierki</option>
<option  value="1542">Art. Spo¿ywcze/S³odycze/Czekolady</option>
<option  value="1543">Art. Spo¿ywcze/S³odycze/Dra¿e, pastylki, orzechy</option>
<option  value="1545">Art. Spo¿ywcze/S³odycze/Pierniki</option>
<option  value="1546">Art. Spo¿ywcze/S³odycze/Toffi, krówki</option>
<option  value="1547">Art. Spo¿ywcze/S³odycze/¯elki, galaretki, pianki</option>
<option  value="2405">Art. Spo¿ywcze/S³odycze/Kosze ze s³odyczami</option>
<option  value="1551">Art. Spo¿ywcze/T³uszcze/Oliwy</option>
<option  value="1553">Art. Spo¿ywcze/Tytoniowe/Cygara</option>
<option  value="1555">Art. Spo¿ywcze/Tytoniowe/Papierosy</option>
<option  value="1556">Art. Spo¿ywcze/Warzywa i owoce</option>
<option  value="1559">Art. Spo¿ywcze/Wêdliny/Kie³basy wieprzowe</option>
<option  value="1560">Art. Spo¿ywcze/Wêdliny/Kie³basy wo³owe</option>
<option  value="1561">Art. Spo¿ywcze/Wêdliny/Wêdliny drobiowe</option>
<option  value="1562">Art. Spo¿ywcze/Wêdliny/Wêdliny wieprzowe</option>
<option  value="1563">Art. Spo¿ywcze/Wêdliny/Wêdliny wo³owe</option>
<option  value="1564">Art. Spo¿ywcze/Wyroby garma¿eryjne</option>
<option  value="1565">Art. Spo¿ywcze/Garma¿eria</option>
<option  value="1573">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Gotowe desery, owoce</option>
<option  value="1574">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Herbatki dla dzieci</option>
<option  value="1576">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Kleiki, kaszki</option>
<option  value="1577">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Mleko zastêpcze</option>
<option  value="1578">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Potrawki, zupki</option>
<option  value="1579">Art. Spo¿ywcze/¯ywno¶æ dla dzieci/Soki dla dzieci</option>
<option  value="2407">Art. Spo¿ywcze/Misd</option>
<option  value="2408">Art. Spo¿ywcze/Kosze upominkowe - spo¿ywcze</option>
<option  value="1494">Art. Spo¿ywcze/Zdrowa ¿ywno¶æ/Musli, otrêby, p³atki</option>
<option  value="3275">Art. Spo¿ywcze/Zdrowa ¿ywno¶æ/Bakalie, nasiona</option>
<option  value="3276">Art. Spo¿ywcze/Zdrowa ¿ywno¶æ/Napoje i syropy</option>
<option  value="3277">Art. Spo¿ywcze/Zdrowa ¿ywno¶æ/Pasty, kremy</option>
<option  value="3278">Art. Spo¿ywcze/Zdrowa ¿ywno¶æ/Produkty sojowe</option>
<option  value="716">Sport, hobby, turystyka/Birofilistyka</option>
<option  value="727">Sport, hobby, turystyka/Numizmatyka/Afryka</option>
<option  value="728">Sport, hobby, turystyka/Numizmatyka/Ameryka Pd. i Karaiby</option>
<option  value="729">Sport, hobby, turystyka/Numizmatyka/Ameryka Pn.</option>
<option  value="730">Sport, hobby, turystyka/Numizmatyka/Australia i Oceania</option>
<option  value="731">Sport, hobby, turystyka/Numizmatyka/Azja</option>
<option  value="732">Sport, hobby, turystyka/Numizmatyka/Europa bez Polski</option>
<option  value="733">Sport, hobby, turystyka/Pami±tki, plakaty</option>
<option  value="734">Sport, hobby, turystyka/Pieni±dz papierowy</option>
<option  value="735">Sport, hobby, turystyka/Pocztówki</option>
<option  value="740">Sport, hobby, turystyka/Znaczki/Ameryka Pd.</option>
<option  value="746">Sport, hobby, turystyka/Znaczki/Polska</option>
<option  value="1315">Sport, hobby, turystyka/Badminton</option>
<option  value="1316">Sport, hobby, turystyka/Baseball</option>
<option  value="1317">Sport, hobby, turystyka/Boks</option>
<option  value="1318">Sport, hobby, turystyka/Deskorolka</option>
<option  value="1319">Sport, hobby, turystyka/Golf</option>
<option  value="1320">Sport, hobby, turystyka/Hokej</option>
<option  value="1321">Sport, hobby, turystyka/Hokej na trawie</option>
<option  value="1323">Sport, hobby, turystyka/Jazda konna</option>
<option  value="1324">Sport, hobby, turystyka/Judo</option>
<option  value="1327">Sport, hobby, turystyka/Kamping i biwak/Termosy, do gotowania</option>
<option  value="1328">Sport, hobby, turystyka/Kamping i biwak/Do spania</option>
<option  value="1330">Sport, hobby, turystyka/Kamping i biwak/Namioty</option>
<option  value="1332">Sport, hobby, turystyka/Kamping i biwak/Plecaki i torby</option>
<option  value="1333">Sport, hobby, turystyka/Kolarstwo</option>
<option  value="1334">Sport, hobby, turystyka/Koszykówka</option>
<option  value="1335">Sport, hobby, turystyka/Lekkoatletyka</option>
<option  value="1336">Sport, hobby, turystyka/Lotnictwo</option>
<option  value="1337">Sport, hobby, turystyka/£ucznictwo</option>
<option  value="1339">Sport, hobby, turystyka/Odzie¿ i obuwie/Fitness</option>
<option  value="1352">Sport, hobby, turystyka/Odzie¿ i obuwie/Kulturystyka</option>
<option  value="1354">Sport, hobby, turystyka/Odzie¿ i obuwie/Narty</option>
<option  value="1355">Sport, hobby, turystyka/Odzie¿ i obuwie/Odzie¿ i obuwie turystyczne</option>
<option  value="1356">Sport, hobby, turystyka/Odzie¿ i obuwie/Paintball</option>
<option  value="1357">Sport, hobby, turystyka/Odzie¿ i obuwie/Pi³ka no¿na</option>
<option  value="1358">Sport, hobby, turystyka/Odzie¿ i obuwie/Pi³ka rêczna</option>
<option  value="1359">Sport, hobby, turystyka/Odzie¿ i obuwie/Rolki</option>
<option  value="1360">Sport, hobby, turystyka/Odzie¿ i obuwie/Siatkówka</option>
<option  value="1361">Sport, hobby, turystyka/Odzie¿ i obuwie/Snowboard</option>
<option  value="1362">Sport, hobby, turystyka/Odzie¿ i obuwie/Tenis sto³owy</option>
<option  value="1363">Sport, hobby, turystyka/Odzie¿ i obuwie/Tenis ziemny</option>
<option  value="1364">Sport, hobby, turystyka/Odzie¿ i obuwie/Uniwersalne</option>
<option  value="1365">Sport, hobby, turystyka/Odzie¿ i obuwie/Wêdkarstwo</option>
<option  value="1366">Sport, hobby, turystyka/Odzie¿ i obuwie/Wspinaczka</option>
<option  value="1367">Sport, hobby, turystyka/Odzie¿ i obuwie/Zapasy</option>
<option  value="1368">Sport, hobby, turystyka/Odzie¿ i obuwie/¯eglarstwo</option>
<option  value="1370">Sport, hobby, turystyka/Pami±tki i puchary</option>
<option  value="1377">Sport, hobby, turystyka/Si³ownia i aerobic/Atlasy i ³awki</option>
<option  value="1380">Sport, hobby, turystyka/Si³ownia i aerobic/Rehabilitacyjne</option>
<option  value="1381">Sport, hobby, turystyka/Si³ownia i aerobic/Rowery treningowe</option>
<option  value="1382">Sport, hobby, turystyka/Si³ownia i aerobic/Steppery</option>
<option  value="1383">Sport, hobby, turystyka/Strzelectwo</option>
<option  value="1384">Sport, hobby, turystyka/Szermierka</option>
<option  value="1385">Sport, hobby, turystyka/¦rodki wspomagaj±ce</option>
<option  value="1391">Sport, hobby, turystyka/Wodne/Kajakarstwo</option>
<option  value="1392">Sport, hobby, turystyka/Wodne/Narty wodne</option>
<option  value="1393">Sport, hobby, turystyka/Wodne/Nurkowanie</option>
<option  value="1394">Sport, hobby, turystyka/Wodne/Pi³ka wodna</option>
<option  value="1395">Sport, hobby, turystyka/Wodne/P³ywanie</option>
<option  value="1396">Sport, hobby, turystyka/Wodne/Surfing</option>
<option  value="1397">Sport, hobby, turystyka/Wodne/Wio¶larstwo</option>
<option  value="1402">Sport, hobby, turystyka/Zimowe/Buty narciarskie</option>
<option  value="1403">Sport, hobby, turystyka/Zimowe/Buty snowboardowe</option>
<option  value="1404">Sport, hobby, turystyka/Zimowe/Gogle</option>
<option  value="1406">Sport, hobby, turystyka/Zimowe/Kije narciarskie</option>
<option  value="1408">Sport, hobby, turystyka/Zimowe/Plecaki</option>
<option  value="1411">Sport, hobby, turystyka/Zimowe/Torby</option>
<option  value="2380">Sport, hobby, turystyka/Zimowe/Wiazania i p³yty</option>
<option  value="1991">Sport, hobby, turystyka/Kartki</option>
<option  value="1998">Sport, hobby, turystyka/Plastyka/Rysunek i grafika/Pastele i kredki</option>
<option  value="1999">Sport, hobby, turystyka/Plastyka/Rysunek i grafika/Narzêdzia do rysunku i kaligrafii</option>
<option  value="2000">Sport, hobby, turystyka/Plastyka/Rysunek i grafika/Papier rysunkowy</option>
<option  value="2009">Sport, hobby, turystyka/Upominki Internetowe/Kubki</option>
<option  value="2010">Sport, hobby, turystyka/Upominki Internetowe/Podk³adki pod myszki</option>
<option  value="2014">Sport, hobby, turystyka/My¶listwo/Lunety celownicze</option>
<option  value="2015">Sport, hobby, turystyka/My¶listwo/Monta¿e</option>
<option  value="3360">Sport, hobby, turystyka/My¶listwo/Galanteria my¶liwska</option>
<option  value="2381">Sport, hobby, turystyka/Rower</option>
<option  value="2386">Sport, hobby, turystyka/Sztuki walki</option>
<option  value="2456">Sport, hobby, turystyka/Instrumenty muzyczne/Gitara i bas/Gitary</option>
<option  value="2459">Sport, hobby, turystyka/Instrumenty muzyczne/Instrumenty smyczkowe</option>
<option  value="2460">Sport, hobby, turystyka/Instrumenty muzyczne/Instrumenty dête</option>
<option  value="2463">Sport, hobby, turystyka/Instrumenty muzyczne/Perkusje/Zestawy perkusyjne</option>
<option  value="2464">Sport, hobby, turystyka/Instrumenty muzyczne/Perkusje/Talerze</option>
<option  value="2465">Sport, hobby, turystyka/Instrumenty muzyczne/Perkusje/Instrumenty perkusyjne</option>
<option  value="2468">Sport, hobby, turystyka/Instrumenty muzyczne/Klawisze/Keyboardy i syntezatory</option>
<option  value="1580">Telefony/Centrale</option>
<option  value="1582">Telefony/Telefaksy</option>
<option  value="1583">Telefony/Telefony bezprzewodowe</option>
<option  value="1584">Telefony/Telefony GSM</option>
<option  value="1590">Telefony/Pre-paid</option>
<option  value="1591">Telefony/Telefony ISDN</option>
<option  value="1592">Telefony/Telefony stacjonarne</option>
<option  value="2410">Telefony/VoIP/Centrale VoIP</option>
<option  value="2411">Telefony/VoIP/Karty pre-paid</option>
<option  value="2412">Telefony/VoIP/Aparaty telefoniczne</option>
<option  value="2437">Kwiaty/Bukiety</option>
<option  value="2438">Kwiaty/Kosze owoców</option>
<option  value="3392">Kwiaty/Kwiaty ciête</option>
<option  value="3393">Kwiaty/Ro¶liny doniczkowe</option>
<option  value="1936">Broñ i Militaria/Wiatrówki karabinki</option>
<option  value="1943">Broñ i Militaria/Wiatrówki pistolety</option>
<option  value="1500015">Broñ i Militaria/Osprzêt do wiatrówek/Kabury i pokrowce</option>
<option  value="1500013">Broñ i Militaria/Osprzêt do wiatrówek/Tarcze i kulochwyty</option>
<option  value="1500012">Broñ i Militaria/Osprzêt do wiatrówek/¦ruty</option>
<option  value="1500011">Broñ i Militaria/Osprzêt do wiatrówek/Konserwacja</option>
<option  value="1500014">Broñ i Militaria/Osprzêt do wiatrówek/Magazynki</option>
<option  value="1945">Broñ i Militaria/Lunety</option>
<option  value="1946">Broñ i Militaria/Amunicja</option>
<option  value="1500005">Broñ i Militaria/Air Soft Gun/Pistolety sprê¿ynowe</option>
<option  value="1500003">Broñ i Militaria/Air Soft Gun/Karabinki ASG</option>
<option  value="1500004">Broñ i Militaria/Air Soft Gun/Amunicja i osprzêt</option>
<option  value="1500006">Broñ i Militaria/Air Soft Gun/Pistolety pneumatyczne</option>
<option  value="1952">Broñ i Militaria/Karabinki elektryczne EAG</option>
<option  value="1953">Broñ i Militaria/Broñ alarmowa</option>
<option  value="1955">Broñ i Militaria/No¿e/Sk³adane</option>
<option  value="1957">Broñ i Militaria/No¿e/Scyzoryki</option>
<option  value="1500010">Broñ i Militaria/No¿e/Miecze</option>
<option  value="1500009">Broñ i Militaria/No¿e/O sta³ej klindze</option>
<option  value="1960">Broñ i Militaria/Paralizatory</option>
<option  value="1961">Broñ i Militaria/Rêczne miotacze gazu</option>
<option  value="1963">Broñ i Militaria/Lornetki</option>
<option  value="1966">Broñ i Militaria/Galanteria</option>
<option  value="1968">Broñ i Militaria/Multitools</option>
<option  value="1974">Broñ i Militaria/Odzie¿ militarna/Koszulki, koszule</option>
<option  value="1977">Broñ i Militaria/Odzie¿ militarna/Buty</option>
<option  value="1979">Broñ i Militaria/Odzie¿ militarna/Kamizelki</option>
<option  value="1981">Broñ i Militaria/Odzie¿ militarna/Plecaki wojskowe</option>
<option  value="1970">Broñ i Militaria/Noktowizory</option>
<option  value="1971">Broñ i Militaria/Teleskopy</option>
<option  value="1500008">Broñ i Militaria/£uki i proce/Proce i akcesoria</option>
<option  value="1500007">Broñ i Militaria/£uki i proce/£uki i akcesoria</option>
<option  value="1983">Broñ i Militaria/Dalmierze</option>
<option  value="1985">Broñ i Militaria/Repliki broni/Broñ bia³a</option>
<option  value="1986">Broñ i Militaria/Repliki broni/Broñ palna</option>
<option  value="1987">Broñ i Militaria/Repliki broni/Zbroje i tarcze</option>
<option  value="1988">Broñ i Militaria/Repliki broni/Miniatury</option>
<option  value="1990">Broñ i Militaria/Wykrywacze metali</option>
<option  value="3328">Broñ i Militaria/Akcesoria militarne</option>
<option  value="3330">Broñ i Militaria/Pistolety gazowe</option>
<option  value="3331">Broñ i Militaria/Pirotechnika</option>
<option  value="2443">Ró¿ne/Okazje specjalne/Balony</option>
<option  value="2445">Ró¿ne/Okazje specjalne/Fajerwerki</option>
<option  value="2446">Ró¿ne/Okazje specjalne/Ozdoby</option>
<option  value="2447">Ró¿ne/Okazje specjalne/Party</option>
<option  value="2448">Ró¿ne/Okazje specjalne/Picnik</option>
<option  value="2449">Ró¿ne/Okazje specjalne/Serwetki</option>
<option  value="2451">Ró¿ne/Okazje specjalne/Zaproszenia</option>
<option  value="4100">Erotyka/Lack/Spodnie i spodenki</option>
<option  value="4126">Erotyka/Latex/Sukienki i spódniczki</option>
<option  value="4128">Erotyka/Latex/Komplety i stroje</option>
<option  value="4132">Erotyka/Prezerwatywy/Normalne</option>
<option  value="4156">Erotyka/Skóra/Ubrania dla Pañ</option>
<option  value="4157">Erotyka/Skóra/Ubrania dla Panów</option>
<option  value="4159">Erotyka/S/M/Baty i packi</option>
<option  value="4160">Erotyka/S/M/Czapki</option>
<option  value="4162">Erotyka/S/M/Maski</option>
<option  value="4163">Erotyka/S/M/Paski i nak³adki</option>
<option  value="4165">Erotyka/S/M/Odzie¿ S/M</option>
<option  value="4177">Erotyka/Zdjêcia/Czasopisma i magazyny</option>
<option  value="4178">Erotyka/Zdjêcia/Na CD</option>
</select>
