<select class=form name="item[interia_category]" size="1"><option value="default">----wybierz----</option>
<option  value="656">Film/Muzyka</option>
<option  value="810">Ksi±¿ki i Czasopisma/Czasopisma/Muzyka</option>
<option  value="1098">Muzyka/Instrumenty/Dête</option>
<option  value="1099">Muzyka/Instrumenty/Elektroniczne</option>
<option  value="1102">Muzyka/Instrumenty/Klawiszowe</option>
<option  value="1103">Muzyka/Instrumenty/Perkusyjne</option>
<option  value="1104">Muzyka/Instrumenty/Smyczkowe</option>
<option  value="1105">Muzyka/Instrumenty/Strunowe</option>
<option  value="1097">Muzyka/Instrumenty/Akcesoria</option>
<option  value="1100">Muzyka/Instrumenty/Inne</option>
<option  value="1107">Muzyka/Nagrania/AcidJazz</option>
<option  value="1108">Muzyka/Nagrania/Alternatywna</option>
<option  value="1109">Muzyka/Nagrania/Ambient</option>
<option  value="1110">Muzyka/Nagrania/Blues</option>
<option  value="1111">Muzyka/Nagrania/Country</option>
<option  value="1112">Muzyka/Nagrania/Dawna</option>
<option  value="1113">Muzyka/Nagrania/Dzieciêca</option>
<option  value="1114">Muzyka/Nagrania/Filmowa</option>
<option  value="1115">Muzyka/Nagrania/Folk</option>
<option  value="1116">Muzyka/Nagrania/Funk</option>
<option  value="1117">Muzyka/Nagrania/Gospel</option>
<option  value="1118">Muzyka/Nagrania/Hip-Hop</option>
<option  value="1119">Muzyka/Nagrania/House</option>
<option  value="1120">Muzyka/Nagrania/Industrial</option>
<option  value="1121">Muzyka/Nagrania/Jazz</option>
<option  value="1122">Muzyka/Nagrania/Jungle</option>
<option  value="1123">Muzyka/Nagrania/Kabaretowa</option>
<option  value="1124">Muzyka/Nagrania/Klasyczna</option>
<option  value="1125">Muzyka/Nagrania/Minimal</option>
<option  value="1126">Muzyka/Nagrania/New Age</option>
<option  value="1127">Muzyka/Nagrania/Opera</option>
<option  value="1128">Muzyka/Nagrania/Piosenka Aktorska i Poezja ¶piewana</option>
<option  value="1129">Muzyka/Nagrania/Pop</option>
<option  value="1130">Muzyka/Nagrania/Reggae</option>
<option  value="1131">Muzyka/Nagrania/Religijna</option>
<option  value="1132">Muzyka/Nagrania/Rhythm</option>
<option  value="1133">Muzyka/Nagrania/Rock</option>
<option  value="1134">Muzyka/Nagrania/Sk³adanka</option>
<option  value="1135">Muzyka/Nagrania/Szanty</option>
<option  value="1136">Muzyka/Nagrania/¦wi±teczna</option>
<option  value="1140">Muzyka/Nagrania/Trip-Hop</option>
<option  value="1141">Muzyka/Nagrania/Teatralna i filmowa</option>
<option  value="1142">Muzyka/Nagrania/Techno</option>
<option  value="1143">Muzyka/Nagrania/Trance</option>
<option  value="1145">Muzyka/Nagrania/Wokalistyka</option>
<option  value="2366">Muzyka/Nagrania/Elektroniczna</option>
<option  value="2367">Muzyka/Nagrania/Rap</option>
<option  value="3226">Muzyka/Nagrania/R &amp; B</option>
<option  value="1139">Muzyka/Nagrania/¦wi±teczna</option>
<option  value="2368">Muzyka/Nagrania/Inne</option>
<option  value="1095">Muzyka/Inne</option>
</select>
