<?php
/**
* Obs³uga klientów.
*
* @author  m@sote.pl
* @version $Id: users.inc,v 1.2 2004/12/20 18:03:01 maroslaw Exp $
* @package    include
*/

/**
* Zarz±dzanie dostêpem do danych klientów i aktualizcj± danych.
* @package users
* @subpackage users
*/
class Users {
    
    /**
    * Konstruktor
    */
    function Users() {
        
    } // end Users()
    
    /**
    * Dodaj klienta do bazy
    */
    function add() {
        
    } // end add()
    
    /**
    * Skasuj klienta z bazy
    */
    function del() {
        
    } // end del()
    
    /**
    * Aktualizuj dane klienta  
    */
    function update() {
        
    } // end update()
    
    /**
    * Zmieñ has³o klienta
    */
    function newPassword() {
        
    } // end newPassword()
    
    /**
    * Przypomnij has³o klienta
    */
    function reminPassword() {
        
    } // end remidPassword()
    
    /**
    * Odczytaj dane klienta
    */
    function getInfo() {
        
    } // end getInfo()
    
    /**
    * Odczytaj transakcje klienta
    */
    function orders() {
        
    } // orders()
    
    /**
    * Odczytaj ilo¶æ punktów klienta
    */
    function points() {
        
    } // end points()
    
    /**
    * Zaloguj klienta/weryfikacja
    */
    function login() {
        
    } // end login()
    
    /**
    * Wyloguj klienta
    */
    function logout() {
        
    } // end logout()
    
    /**
    * Rabat klienta/grupa rabatowa
    */
    function discount() {
        
    } // end discount()
    
} // end class Users
?>
