<select class=form name="item[wp_category]" size="1"><option value="default">----wybierz----
<option  value="45158">/Zakupy/Harry Potter/Muzyka/
<option  value="2543">/Zakupy/Ksi±¿ki/Kultura i sztuka/Muzyka/
<option  value="2615">/Zakupy/Muzyka/Alternatywa/
<option  value="2616">/Zakupy/Muzyka/Ambient/
<option  value="2617">/Zakupy/Muzyka/Big Beat/
<option  value="2618">/Zakupy/Muzyka/Blues/
<option  value="2619">/Zakupy/Muzyka/Breakbeat/
<option  value="2620">/Zakupy/Muzyka/Classic/
<option  value="2621">/Zakupy/Muzyka/Country/
<option  value="2622">/Zakupy/Muzyka/Dance/
<option  value="11395">/Zakupy/Muzyka/Dla dzieci/
<option  value="2624">/Zakupy/Muzyka/Drum n bass/
<option  value="2625">/Zakupy/Muzyka/Easy listening/
<option  value="2626">/Zakupy/Muzyka/Electro/
<option  value="2627">/Zakupy/Muzyka/Electronica/
<option  value="2628">/Zakupy/Muzyka/Ethno/
<option  value="2629">/Zakupy/Muzyka/Folk/
<option  value="16951">/Zakupy/Muzyka/Gad¿ety/
<option  value="2630">/Zakupy/Muzyka/Hip Hop/
<option  value="2631">/Zakupy/Muzyka/House/
<option  value="4795">/Zakupy/Muzyka/Inna/
<option  value="2632">/Zakupy/Muzyka/Jazz/
<option  value="2633">/Zakupy/Muzyka/Kabaret/
<option  value="11393">/Zakupy/Muzyka/Klasyka/
<option  value="11391">/Zakupy/Muzyka/Kolêdy/
<option  value="2634">/Zakupy/Muzyka/Metal/
<option  value="2635">/Zakupy/Muzyka/Musical/
<option  value="11394">/Zakupy/Muzyka/New Age/
<option  value="11392">/Zakupy/Muzyka/Piosenka biesiadna/
<option  value="2636">/Zakupy/Muzyka/Poezja/
<option  value="2637">/Zakupy/Muzyka/Pop/
<option  value="11396">/Zakupy/Muzyka/Powie¶æ radiowa/
<option  value="2638">/Zakupy/Muzyka/R & B/
<option  value="2639">/Zakupy/Muzyka/Rap/
<option  value="2640">/Zakupy/Muzyka/Reggae/
<option  value="2641">/Zakupy/Muzyka/Rock/
<option  value="2642">/Zakupy/Muzyka/Sk³adanka/
<option  value="2643">/Zakupy/Muzyka/Soul/
<option  value="2644">/Zakupy/Muzyka/Soundtrack/
<option  value="11411">/Zakupy/Muzyka/Szanty/
<option  value="2645">/Zakupy/Muzyka/Techno/
<option  value="2646">/Zakupy/Muzyka/Trance/
<option  value="2647">/Zakupy/Muzyka/Trip Hop/
<option  value="5702">/Zakupy/Niewidoczne/Prezenty gwiazdkowe/Muzyka/
</select>
